### ISSUE TITLE
Fix error: VeloxRuntimeError: !leftKeys_.empty() in TPC-H tests

### ISSUE THREAD

**Issue by aditi-pandit** [facebookincubator/velox#222]
Several TPC-H benchmark queries (Q2, Q11, Q17, Q20) failed on PrestoCPP with the error:
VeloxRuntimeError: !leftKeys_.empty()

Stack trace 

Caused by: java.lang.RuntimeException: !leftKeys_.empty()
at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:124)
at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:552)
at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:520)
at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:148)
... 28 more
Caused by: VeloxRuntimeError: !leftKeys_.empty()

Steps to reproduce :  Run unit tests testTpchQ2, testTpchQ11, testTpchQ17 and testTpchQ20 in
java/presto-native-tests/src/test/java/com/facebook/presto/nativeworker/TestHiveTpchQueries.java

**Comment by mbasmanova** [comment]
This has been fixed.
