### ISSUE TITLE
How to generate parquet data to run tpc-h benchmark

### ISSUE THREAD

**Issue by ruclz** [facebookincubator/velox#2614]
I want to run tpc-h benchmark. Before, I generated the parquet data by the pr (https://github.com/databricks/spark-sql-perf). 
But it seems that the data can't be read by velox.  So how can i  generate tpc-h parquet data? Thank you.

**Comment by ruclz** [comment]
Yes, but when I generate partsupp table and lineitem table, it occurs errors.  I generate TPC-H partquet data by insert hive parquet table from table tpc-h connector table in Presto.   
SQL:  Insert into  hive.tpch.partsupp_par select * from tpch.sf10.partsupp;
Now, I don't know how to fix the bug. Thank you.

2022-09-23T09:41:24.523+0800    ERROR   SplitRunner-46-164      com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20220923_014049_00004_vp2ur.1.0.0-16  (start = 3.22959093759261E8, wall = 33179 ms, cpu = 28806 ms, wait = 37 ms, calls = 32)
java.lang.ArrayIndexOutOfBoundsException: 118794
        at org.apache.parquet.column.values.dictionary.DictionaryValuesWriter$PlainLongDictionaryValuesWriter.fallBackDictionaryEncodedData(DictionaryValuesWriter.java:397)
        at org.apache.parquet.column.values.dictionary.DictionaryValuesWriter.fallBackAllValuesTo(DictionaryValuesWriter.java:130)
        at org.apache.parquet.column.values.fallback.FallbackValuesWriter.fallBack(FallbackValuesWriter.java:155)
        at org.apache.parquet.column.values.fallback.FallbackValuesWriter.checkFallback(FallbackValuesWriter.java:149)
        at org.apache.parquet.column.values.fallback.FallbackValuesWriter.writeLong(FallbackValuesWriter.java:187)
        at com.facebook.presto.parquet.writer.valuewriter.BigintValueWriter.write(BigintValueWriter.java:40)
        at com.facebook.presto.parquet.writer.PrimitiveColumnWriter.writeBlock(PrimitiveColumnWriter.java:124)
        at com.facebook.presto.parquet.writer.ParquetWriter.writeChunk(ParquetWriter.java:162)
        at com.facebook.presto.parquet.writer.ParquetWriter.write(ParquetWriter.java:152)
        at com.facebook.presto.hive.parquet.ParquetFileWriter.appendRows(ParquetFileWriter.java:107)
        at com.facebook.presto.hive.HiveWriter.append(HiveWriter.java:95)
        at com.facebook.presto.hive.HivePageSink.writePage(HivePageSink.java:403)
        at com.facebook.presto.hive.HivePageSink.doAppend(HivePageSink.java:355)
        at com.facebook.presto.hive.HivePageSink.lambda$appendPage$4(HivePageSink.java:341)
        at com.facebook.presto.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:24)
        at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
        at com.facebook.presto.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:23)
        at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:86)
        at com.facebook.presto.hive.HivePageSink.appendPage(HivePageSink.java:341)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:66)
        at com.facebook.presto.operator.TableWriterOperator.addInput(TableWriterOperator.java:341)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:436)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:309)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:730)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:302)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:166)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
        at com.facebook.presto.$gen.Presto_0_276_4d6bb7c____20220923_013435_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)


2022-09-23T09:41:24.544+0800    ERROR   remote-task-callback-13 com.facebook.presto.execution.StageExecutionStateMachine    Stage execution 20220923_014049_00004_vp2ur.1.0 failed
java.lang.ArrayIndexOutOfBoundsException: 118794
        at org.apache.parquet.column.values.dictionary.DictionaryValuesWriter$PlainLongDictionaryValuesWriter.fallBackDictionaryEncodedData(DictionaryValuesWriter.java:397)
        at org.apache.parquet.column.values.dictionary.DictionaryValuesWriter.fallBackAllValuesTo(DictionaryValuesWriter.java:130)
        at org.apache.parquet.column.values.fallback.FallbackValuesWriter.fallBack(FallbackValuesWriter.java:155)
        at org.apache.parquet.column.values.fallback.FallbackValuesWriter.checkFallback(FallbackValuesWriter.java:149)
        at org.apache.parquet.column.values.fallback.FallbackValuesWriter.writeLong(FallbackValuesWriter.java:187)
        at com.facebook.presto.parquet.writer.valuewriter.BigintValueWriter.write(BigintValueWriter.java:40)
        at com.facebook.presto.parquet.writer.PrimitiveColumnWriter.writeBlock(PrimitiveColumnWriter.java:124)
        at com.facebook.presto.parquet.writer.ParquetWriter.writeChunk(ParquetWriter.java:162)
        at com.facebook.presto.parquet.writer.ParquetWriter.write(ParquetWriter.java:152)
        at com.facebook.presto.hive.parquet.ParquetFileWriter.appendRows(ParquetFileWriter.java:107)
        at com.facebook.presto.hive.HiveWriter.append(HiveWriter.java:95)
        at com.facebook.presto.hive.HivePageSink.writePage(HivePageSink.java:403)
        at com.facebook.presto.hive.HivePageSink.doAppend(HivePageSink.java:355)
        at com.facebook.presto.hive.HivePageSink.lambda$appendPage$4(HivePageSink.java:341)
        at com.facebook.presto.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:24)
        at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
        at com.facebook.presto.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:23)
        at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:86)
        at com.facebook.presto.hive.HivePageSink.appendPage(HivePageSink.java:341)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:66)
        at com.facebook.presto.operator.TableWriterOperator.addInput(TableWriterOperator.java:341)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:436)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:309)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:730)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:302)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:166)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
        at com.facebook.presto.$gen.Presto_0_276_4d6bb7c____20220923_013435_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

**Comment by majetideepak** [comment]
Can you try CTAS? We use CTAS for testing as well.
https://github.com/prestodb/presto/blob/95237f10d01b1090638421b3a84490f617258c43/presto-native-execution/src/test/java/com/facebook/presto/hive/HiveExternalWorkerQueryRunner.java#L418

**Comment by ruclz** [comment]
Thank you, very much. I will try CTAS.

**Comment by ruclz** [comment]
Succeed. Thank you very much @majetideepak. And if  you  generate TPC-H partquet data by insert hive parquet table from tpc-h connector table in Presto, please set hive.parquet.optimized-writer.enabled=false(default false). If using native parquet writer. Maybe errors when generate partsupp and  lineitem table.
