### ISSUE TITLE
ASAN error in DecodedVector::copyNulls()

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#2973]
This error can only be reproduced internally right now because `--repro_persist_path` was not triggered. It can be reproduced by checking out `078ffeddc` in the internal repository and then running `velox/expression/tests/velox_expression_fuzzer_test  --velox_fuzzer_enable_complex_types --velox_fuzzer_max_level_of_nesting 2 --only "array_join,array_except" --seed 3225400466`.

```
======> Started iteration 0 (seed: 3225400466)
I1026 13:50:26.886240 2940012 ExpressionVerifier.cpp:130] Executing expression: array_join(array_except(10 elements starting at 610 {0.1090278515342088, 0.6624547903983469, 0.31382952668828856, 0.2787927889051304, 0.5410698337010078, ...},10 elements starting at 220 {[220->732] [732->74] [74->198] [198->112] [112->505] 0.09034958418716654, [221->300] [300->788] [788->243] [243->559] [559->361] 0.09034958418716654, null, [223->160] null, [224->833] [833->496] null, ...}),"c0","c1")
I1026 13:50:26.886771 2940012 ExpressionVerifier.cpp:133] 2 vectors as input:
I1026 13:50:26.886828 2940012 ExpressionVerifier.cpp:135] 	[DICTIONARY VARCHAR: 100 elements, 6 nulls], [FLAT VARCHAR: 100 elements, 9 nulls]
I1026 13:50:26.886907 2940012 ExpressionVerifier.cpp:135] 	[FLAT VARCHAR: 100 elements, 9 nulls]
=================================================================
==2940012==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c00002f400 at pc 0x00000037f3da bp 0x7fffbe1af0c0 sp 0x7fffbe1ae870
READ of size 88 at 0x60c00002f400 thread T0
SCARINESS: 26 (multi-byte-read-heap-buffer-overflow)
    #0 0x37f3d9 in __asan_memmove (/data/users/weihe/fbsource/fbcode/buck-out/dev/gen/aab7ed39/velox/expression/tests/velox_expression_fuzzer_test+0x37f3d9)
    #1 0x7f229c3a4a06 in unsigned long* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<unsigned long>(unsigned long const*, unsigned long const*, unsigned long*) third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_algobase.h:431
    #2 0x7f229c3a49b4 in unsigned long* std::__copy_move_a2<false, unsigned long const*, unsigned long*>(unsigned long const*, unsigned long const*, unsigned long*) third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_algobase.h:494
    #3 0x7f229c3a4824 in unsigned long* std::__copy_move_a1<false, unsigned long const*, unsigned long*>(unsigned long const*, unsigned long const*, unsigned long*) third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_algobase.h:522
    #4 0x7f229c3d54c3 in unsigned long* std::__copy_move_a<false, unsigned long const*, unsigned long*>(unsigned long const*, unsigned long const*, unsigned long*) third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_algobase.h:530
    #5 0x7f229c3cea09 in unsigned long* std::copy<unsigned long const*, unsigned long*>(unsigned long const*, unsigned long const*, unsigned long*) third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_algobase.h:619
    #6 0x7f229c3ce6e6 in facebook::velox::DecodedVector::copyNulls(int) velox/vector/DecodedVector.cpp:144
    #7 0x7f229c3d1960 in facebook::velox::DecodedVector::setFlatNulls(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*) velox/vector/DecodedVector.cpp:364
    #8 0x7f229c3cc9c0 in facebook::velox::DecodedVector::setBaseData(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*) velox/vector/DecodedVector.cpp:392
    #9 0x7f229c3cdb6a in facebook::velox::DecodedVector::combineWrappers(facebook::velox::BaseVector const*, facebook::velox::SelectivityVector const*, int) velox/vector/DecodedVector.cpp:205
    #10 0x7f229c3cc162 in facebook::velox::DecodedVector::decode(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*, bool) velox/vector/DecodedVector.cpp:106
    #11 0x7f22a4c62e84 in facebook::velox::DecodedVector::decode(facebook::velox::BaseVector const&, bool) velox/vector/DecodedVector.h:82
    #12 0x7f22a4c62d71 in facebook::velox::exec::detail::decode(facebook::velox::DecodedVector&, facebook::velox::BaseVector const&) velox/expression/VectorReaders.h:271
    #13 0x7f22a4dbca97 in facebook::velox::exec::VectorReader<facebook::velox::Array<double> >::VectorReader(facebook::velox::DecodedVector const*) velox/expression/VectorReaders.h:385
    #14 0x7f22a51c078a in void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::ArrayJoinFunction<facebook::velox::exec::VectorExec, double>, facebook::velox::exec::VectorExec, facebook::velox::Varchar, facebook::velox::Array<double>, facebook::velox::Varchar, facebook::velox::Varchar> >::unpack<0, false>(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::ArrayJoinFunction<facebook::velox::exec::VectorExec, double>, facebook::velox::exec::VectorExec, facebook::velox::Varchar, facebook::velox::Array<double>, facebook::velox::Varchar, facebook::velox::Varchar> >::ApplyContext&, std::vector<std::optional<facebook::velox::exec::LocalDecodedVector>, std::allocator<std::optional<facebook::velox::exec::LocalDecodedVector> > >&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > > const&) const velox/expression/SimpleFunctionAdapter.h:507
    #15 0x7f22a51bea6e in facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::ArrayJoinFunction<facebook::velox::exec::VectorExec, double>, facebook::velox::exec::VectorExec, facebook::velox::Varchar, facebook::velox::Array<double>, facebook::velox::Varchar, facebook::velox::Varchar> >::apply(facebook::velox::SelectivityVector const&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&, std::shared_ptr<facebook::velox::Type const> const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) const velox/expression/SimpleFunctionAdapter.h:342
    #16 0x7f229cfcd591 in facebook::velox::exec::Expr::applyFunction(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1440
    #17 0x7f229cfd01ab in facebook::velox::exec::Expr::evalAll(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1264
    #18 0x7f229cfd71fc in facebook::velox::exec::Expr::evalWithNulls(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:993
    #19 0x7f229cfd17c1 in facebook::velox::exec::Expr::evalEncodings(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:883
    #20 0x7f229cfce7ea in facebook::velox::exec::Expr::eval(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&, bool) velox/expression/Expr.cpp:557
    #21 0x7f229cfdeaef in facebook::velox::exec::ExprSet::eval(int, int, bool, facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&) velox/expression/Expr.cpp:1639
    #22 0x7f229abc8135 in facebook::velox::exec::ExprSet::eval(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&) velox/expression/Expr.h:478
    #23 0x7f229abc4b36 in facebook::velox::test::ExpressionVerifier::verify(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, std::shared_ptr<facebook::velox::RowVector> const&, std::shared_ptr<facebook::velox::BaseVector>&&, bool) velox/expression/tests/ExpressionVerifier.cpp:177
    #24 0x7f22a0401986 in facebook::velox::test::ExpressionFuzzer::go() velox/expression/tests/ExpressionFuzzer.cpp:727
    #25 0x7f22a0444cfd in facebook::velox::test::expressionFuzzer(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<facebook::velox::exec::FunctionSignature const*, std::allocator<facebook::velox::exec::FunctionSignature const*> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<facebook::velox::exec::FunctionSignature const*, std::allocator<facebook::velox::exec::FunctionSignature const*> > > > >, unsigned long) velox/expression/tests/ExpressionFuzzer.cpp:754
    #26 0x2c30e3 in FuzzerRunner::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) velox/expression/tests/FuzzerRunner.h:108
    #27 0x2c29ac in main velox/expression/tests/ExpressionFuzzerTest.cpp:57
    #28 0x7f229daa2656 in __libc_start_call_main /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #29 0x7f229daa2717 in __libc_start_main_impl /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../csu/libc-start.c:409:3
    #30 0x2b8b80 in _start /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/x86_64/start.S:116

0x60c00002f400 is located 0 bytes to the right of 128-byte region [0x60c00002f380,0x60c00002f400)
allocated by thread T0 here:
    #0 0x37fe5f in malloc (/data/users/weihe/fbsource/fbcode/buck-out/dev/gen/aab7ed39/velox/expression/tests/velox_expression_fuzzer_test+0x37fe5f)
    #1 0x7f229a94ffc8 in facebook::velox::memory::MemoryAllocator::alloc(long) velox/common/memory/Memory.cpp:86
    #2 0x7f229a97a66f in void* facebook::velox::memory::MemoryPoolImpl<facebook::velox::memory::MemoryAllocator, (unsigned short)16>::allocAligned<(unsigned short)16>(facebook::velox::memory::MemoryPoolImpl<facebook::velox::memory::MemoryAllocator, (unsigned short)16>::ALIGNER<(unsigned short)16>, long) velox/common/memory/Memory.h:535
    #3 0x7f229a97670e in facebook::velox::memory::MemoryPoolImpl<facebook::velox::memory::MemoryAllocator, (unsigned short)16>::allocate(long) velox/common/memory/Memory.h:687
    #4 0x7f22a044a7bd in facebook::velox::memory::ScopedMemoryPool::allocate(long) velox/common/memory/Memory.h:194
    #5 0x7f22a0d841ea in boost::intrusive_ptr<facebook::velox::Buffer> facebook::velox::AlignedBuffer::allocate<char>(unsigned long, facebook::velox::memory::MemoryPool*, std::optional<char> const&) velox/buffer/Buffer.h:325
    #6 0x7f22a0d814e2 in boost::intrusive_ptr<facebook::velox::Buffer> facebook::velox::AlignedBuffer::allocate<bool>(unsigned long, facebook::velox::memory::MemoryPool*, std::optional<bool> const&) velox/buffer/Buffer.h:526
    #7 0x7f22a0e4b58f in facebook::velox::functions::(anonymous namespace)::ArrayIntersectExceptFunction<false, double>::apply(facebook::velox::SelectivityVector const&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&, std::shared_ptr<facebook::velox::Type const> const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) const velox/functions/prestosql/ArrayIntersectExcept.cpp:158
    #8 0x7f229cfcd591 in facebook::velox::exec::Expr::applyFunction(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1440
    #9 0x7f229cfda6d1 in facebook::velox::exec::Expr::applyFunctionWithPeeling(facebook::velox::SelectivityVector const&, facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1420
    #10 0x7f229cfd0170 in facebook::velox::exec::Expr::evalAll(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1263
    #11 0x7f229cfd7464 in facebook::velox::exec::Expr::evalWithNulls(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1001
    #12 0x7f229cfd17c1 in facebook::velox::exec::Expr::evalEncodings(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:883
    #13 0x7f229cfce7ea in facebook::velox::exec::Expr::eval(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&, bool) velox/expression/Expr.cpp:557
    #14 0x7f229d03e7d8 in facebook::velox::exec::(anonymous namespace)::tryFoldIfConstant(std::shared_ptr<facebook::velox::exec::Expr> const&, facebook::velox::exec::(anonymous namespace)::Scope*) velox/expression/ExprCompiler.cpp:351
    #15 0x7f229d02de0e in facebook::velox::exec::(anonymous namespace)::compileExpression(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, facebook::velox::exec::(anonymous namespace)::Scope*, facebook::velox::core::QueryConfig const&, facebook::velox::memory::MemoryPool*, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) velox/expression/ExprCompiler.cpp:508
    #16 0x7f229d038b1c in facebook::velox::exec::(anonymous namespace)::compileInputs(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, facebook::velox::exec::(anonymous namespace)::Scope*, facebook::velox::core::QueryConfig const&, facebook::velox::memory::MemoryPool*, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) velox/expression/ExprCompiler.cpp:178
    #17 0x7f229d02bbbb in facebook::velox::exec::(anonymous namespace)::compileExpression(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, facebook::velox::exec::(anonymous namespace)::Scope*, facebook::velox::core::QueryConfig const&, facebook::velox::memory::MemoryPool*, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) velox/expression/ExprCompiler.cpp:409
    #18 0x7f229d02a43e in facebook::velox::exec::compileExpressions(std::vector<std::shared_ptr<facebook::velox::core::ITypedExpr const>, std::allocator<std::shared_ptr<facebook::velox::core::ITypedExpr const> > > const&, facebook::velox::core::ExecCtx*, facebook::velox::exec::ExprSet*, bool) velox/expression/ExprCompiler.cpp:565
    #19 0x7f229cfddacf in facebook::velox::exec::ExprSet::ExprSet(std::vector<std::shared_ptr<facebook::velox::core::ITypedExpr const>, std::allocator<std::shared_ptr<facebook::velox::core::ITypedExpr const> > > const&, facebook::velox::core::ExecCtx*, bool) velox/expression/Expr.cpp:1543
    #20 0x7f229abc49ec in facebook::velox::test::ExpressionVerifier::verify(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, std::shared_ptr<facebook::velox::RowVector> const&, std::shared_ptr<facebook::velox::BaseVector>&&, bool) velox/expression/tests/ExpressionVerifier.cpp:172
    #21 0x7f22a0401986 in facebook::velox::test::ExpressionFuzzer::go() velox/expression/tests/ExpressionFuzzer.cpp:727
    #22 0x7f22a0444cfd in facebook::velox::test::expressionFuzzer(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<facebook::velox::exec::FunctionSignature const*, std::allocator<facebook::velox::exec::FunctionSignature const*> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<facebook::velox::exec::FunctionSignature const*, std::allocator<facebook::velox::exec::FunctionSignature const*> > > > >, unsigned long) velox/expression/tests/ExpressionFuzzer.cpp:754
    #23 0x2c30e3 in FuzzerRunner::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) velox/expression/tests/FuzzerRunner.h:108
    #24 0x2c29ac in main velox/expression/tests/ExpressionFuzzerTest.cpp:57
    #25 0x7f229daa2656 in __libc_start_call_main /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #26 0x7f229daa2717 in __libc_start_main_impl /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../csu/libc-start.c:409:3
    #27 0x2b8b80 in _start /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/x86_64/start.S:116

SUMMARY: AddressSanitizer: heap-buffer-overflow (/data/users/weihe/fbsource/fbcode/buck-out/dev/gen/aab7ed39/velox/expression/tests/velox_expression_fuzzer_test+0x37f3d9) in __asan_memmove
Shadow bytes around the buggy address:
  0x0c187fffde30: 00 00 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
  0x0c187fffde40: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c187fffde50: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c187fffde60: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c187fffde70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c187fffde80:[fa]fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c187fffde90: 00 00 00 00 00 00 00 00 fa fa fa fa fa fa fa fa
  0x0c187fffdea0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c187fffdeb0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c187fffdec0: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
  0x0c187fffded0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2940012==ABORTING
```

**Comment by mbasmanova** [comment]
Similar to #2975, but the problem is in "end()" function.

CC: @laithsakka @Yuhta
