### ISSUE TITLE
SEGV in bits::isBitSet<unsigned long>()

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#2975]
This error can only be reproduced internally because `--repro_persist_path` doesn't support Timestamp yet. 

Check out 078ffeddc and run:

```
buck run velox/expression/tests:velox_expression_fuzzer_test -- --velox_fuzzer_enable_complex_types --velox_fuzzer_max_level_of_nesting 2 --only "array_join,array_except" --seed 2832028781
```

```
======> Started iteration 0 (seed: 2832028781)
I1026 14:04:03.342792 3001321 ExpressionVerifier.cpp:130] Executing expression: array_join(array_except(10 elements starting at 40 {210019122, 3612193872, 2263278369, 1821775720, 3654387697, ...},10 elements starting at 80 {676256613, 676256613, 676256613, 676256613, 676256613, ...}),array_join(10 elements starting at 520 {2095-08-20T00:53:54.529909765, null, 2014-10-18T18:55:43.274982846, 2008-09-23T23:21:14.416227422, 2082-06-26T00:46:28.029925367, ...},"c0"))
I1026 14:04:03.343211 3001321 ExpressionVerifier.cpp:133] 1 vectors as input:
I1026 14:04:03.343279 3001321 ExpressionVerifier.cpp:135] 	[DICTIONARY VARCHAR: 100 elements, 9 nulls], [CONSTANT VARCHAR: 100 elements, >_sGe28<St*&!NQgpB%{\Zv@9cO%`1A7#'_aOG`U8DaV0t4\:-q'hA6nLy7Han"-\/F1%fr8)"5!i4";4jke]
AddressSanitizer:DEADLYSIGNAL
=================================================================
==3001321==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x7ff6da531a27 bp 0x7ffec1ebb410 sp 0x7ffec1ebb3c0 T0)
==3001321==The signal is caused by a READ memory access.
==3001321==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
SCARINESS: 20 (wild-addr-read)
    #0 0x7ff6da531a27 in bool facebook::velox::bits::isBitSet<unsigned long>(unsigned long const*, int) velox/common/base/BitUtil.h:34
    #1 0x7ff6da5313aa in facebook::velox::bits::isBitNull(unsigned long const*, int) velox/common/base/Nulls.h:38
    #2 0x7ff6dad61432 in facebook::velox::DecodedVector::setFlatNulls(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*)::$_3::operator()(int) const velox/vector/DecodedVector.cpp:370
    #3 0x7ff6dad53f6e in void facebook::velox::(anonymous namespace)::applyToRows<facebook::velox::DecodedVector::setFlatNulls(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*)::$_3>(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*, facebook::velox::DecodedVector::setFlatNulls(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*)::$_3&&) velox/vector/DecodedVector.cpp:49
    #4 0x7ff6dad53adf in facebook::velox::DecodedVector::setFlatNulls(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*) velox/vector/DecodedVector.cpp:368
    #5 0x7ff6dad4e9c0 in facebook::velox::DecodedVector::setBaseData(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*) velox/vector/DecodedVector.cpp:392
    #6 0x7ff6dad4fb6a in facebook::velox::DecodedVector::combineWrappers(facebook::velox::BaseVector const*, facebook::velox::SelectivityVector const*, int) velox/vector/DecodedVector.cpp:205
    #7 0x7ff6dad4e162 in facebook::velox::DecodedVector::decode(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*, bool) velox/vector/DecodedVector.cpp:106
    #8 0x7ff6e35e4e84 in facebook::velox::DecodedVector::decode(facebook::velox::BaseVector const&, bool) velox/vector/DecodedVector.h:82
    #9 0x7ff6e35e4d71 in facebook::velox::exec::detail::decode(facebook::velox::DecodedVector&, facebook::velox::BaseVector const&) velox/expression/VectorReaders.h:271
    #10 0x7ff6e36b5737 in facebook::velox::exec::VectorReader<facebook::velox::Array<long> >::VectorReader(facebook::velox::DecodedVector const*) velox/expression/VectorReaders.h:385
    #11 0x7ff6e3a1893a in void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::ArrayJoinFunction<facebook::velox::exec::VectorExec, long>, facebook::velox::exec::VectorExec, facebook::velox::Varchar, facebook::velox::Array<long>, facebook::velox::Varchar> >::unpack<0, true>(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::ArrayJoinFunction<facebook::velox::exec::VectorExec, long>, facebook::velox::exec::VectorExec, facebook::velox::Varchar, facebook::velox::Array<long>, facebook::velox::Varchar> >::ApplyContext&, std::vector<std::optional<facebook::velox::exec::LocalDecodedVector>, std::allocator<std::optional<facebook::velox::exec::LocalDecodedVector> > >&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > > const&) const velox/expression/SimpleFunctionAdapter.h:507
    #12 0x7ff6e3a16fdc in facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::ArrayJoinFunction<facebook::velox::exec::VectorExec, long>, facebook::velox::exec::VectorExec, facebook::velox::Varchar, facebook::velox::Array<long>, facebook::velox::Varchar> >::apply(facebook::velox::SelectivityVector const&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&, std::shared_ptr<facebook::velox::Type const> const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) const velox/expression/SimpleFunctionAdapter.h:338
    #13 0x7ff6db94f591 in facebook::velox::exec::Expr::applyFunction(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1440
    #14 0x7ff6db95c6d1 in facebook::velox::exec::Expr::applyFunctionWithPeeling(facebook::velox::SelectivityVector const&, facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1420
    #15 0x7ff6db952170 in facebook::velox::exec::Expr::evalAll(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1263
    #16 0x7ff6db959464 in facebook::velox::exec::Expr::evalWithNulls(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1001
    #17 0x7ff6db958859 in facebook::velox::exec::Expr::evalWithMemo(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1081
    #18 0x7ff6db9533d5 in facebook::velox::exec::Expr::evalEncodings(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:868
    #19 0x7ff6db9507ea in facebook::velox::exec::Expr::eval(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&, bool) velox/expression/Expr.cpp:557
    #20 0x7ff6db960aef in facebook::velox::exec::ExprSet::eval(int, int, bool, facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&) velox/expression/Expr.cpp:1639
    #21 0x7ff6d954a135 in facebook::velox::exec::ExprSet::eval(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&) velox/expression/Expr.h:478
    #22 0x7ff6d9546b36 in facebook::velox::test::ExpressionVerifier::verify(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, std::shared_ptr<facebook::velox::RowVector> const&, std::shared_ptr<facebook::velox::BaseVector>&&, bool) velox/expression/tests/ExpressionVerifier.cpp:177
    #23 0x7ff6ded83986 in facebook::velox::test::ExpressionFuzzer::go() velox/expression/tests/ExpressionFuzzer.cpp:727
    #24 0x7ff6dedc6cfd in facebook::velox::test::expressionFuzzer(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<facebook::velox::exec::FunctionSignature const*, std::allocator<facebook::velox::exec::FunctionSignature const*> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<facebook::velox::exec::FunctionSignature const*, std::allocator<facebook::velox::exec::FunctionSignature const*> > > > >, unsigned long) velox/expression/tests/ExpressionFuzzer.cpp:754
    #25 0x2c30e3 in FuzzerRunner::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) velox/expression/tests/FuzzerRunner.h:108
    #26 0x2c29ac in main velox/expression/tests/ExpressionFuzzerTest.cpp:57
    #27 0x7ff6dc424656 in __libc_start_call_main /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #28 0x7ff6dc424717 in __libc_start_main_impl /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../csu/libc-start.c:409:3
    #29 0x2b8b80 in _start /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/x86_64/start.S:116

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV velox/common/base/BitUtil.h:34 in bool facebook::velox::bits::isBitSet<unsigned long>(unsigned long const*, int)
==3001321==ABORTING
```

**Comment by mbasmanova** [comment]
Looks like this bug was introduced in #2666

The new function, applyToRows takes optional SelectivityVector and an "arbitrary" vector. If SelectivityVector is null, the function run on all rows in [0, vector->size()). However, vector can be much larger than the set of rows that need to be decoded (DecodedVector::size_).

CC: @laithsakka @Yuhta
