### ISSUE TITLE
DecodedVector.cpp:339:9: runtime error: null pointer passed as argument 2, which is declared to never be null

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#2982]
Repro:

```
TEST_F(DecodedVectorTest, emptyDictionary) {
  auto vector = std::make_shared<DictionaryVector<int64_t>>(
      pool(),
      nullptr,
      0,
      BaseVector::wrapInDictionary(
          makeNulls(10, nullEvery(3)),
          makeIndicesInReverse(10),
          10,
          BaseVector::wrapInConstant(
              10, 0, makeFlatVector<int64_t>({1, 2, 3}))),
      allocateIndices(0, pool()));
  DecodedVector decoded(*vector);
}

velox/vector/DecodedVector.cpp:339:9: runtime error: null pointer passed as argument 2, which is declared to never be null
/data/users/mbasmanova/fbsource/fbcode/third-party-buck/platform010/build/glibc/include/string.h:44:28: note: nonnull attribute specified here
    #0 0x7f244e6968be in facebook::velox::DecodedVector::makeIndicesMutable() velox/vector/DecodedVector.cpp:337
    #1 0x7f244e69781a in facebook::velox::DecodedVector::setBaseDataForConstant(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*) velox/vector/DecodedVector.cpp:435
    #2 0x7f244e69199c in facebook::velox::DecodedVector::setBaseData(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*) velox/vector/DecodedVector.cpp:408
    #3 0x7f244e692ba9 in facebook::velox::DecodedVector::combineWrappers(facebook::velox::BaseVector const*, facebook::velox::SelectivityVector const*, int) velox/vector/DecodedVector.cpp:210
    #4 0x7f244e69116a in facebook::velox::DecodedVector::decode(facebook::velox::BaseVector const&, facebook::velox::SelectivityVector const*, bool) velox/vector/DecodedVector.cpp:109
    #5 0x9ed240 in facebook::velox::DecodedVector::DecodedVector(facebook::velox::BaseVector const&, bool) velox/vector/DecodedVector.h:69
    #6 0x591550 in facebook::velox::test::DecodedVectorTest_emptyDictionary_Test::TestBody() velox/vector/tests/DecodedVectorTest.cpp:830
    #7 0x7f244d2e5ad5 in testing::Test::Run() /home/engshare/third-party2/googletest/1.11.0/src/googletest/googletest/src/gtest.cc:2682:50
    #8 0x7f244d2e5ad5 in testing::Test::Run() /home/engshare/third-party2/googletest/1.11.0/src/googletest/googletest/src/gtest.cc:2672:6
    #9 0x7f244d2e5c64 in testing::TestInfo::Run() /home/engshare/third-party2/googletest/1.11.0/src/googletest/googletest/src/gtest.cc:2861:14
    #10 0x7f244d2e5c64 in testing::TestInfo::Run() /home/engshare/third-party2/googletest/1.11.0/src/googletest/googletest/src/gtest.cc:2833:6
    #11 0x7f244d2e6321 in testing::TestSuite::Run() /home/engshare/third-party2/googletest/1.11.0/src/googletest/googletest/src/gtest.cc:3015:31
    #12 0x7f244d2e6321 in testing::TestSuite::Run() /home/engshare/third-party2/googletest/1.11.0/src/googletest/googletest/src/gtest.cc:2993:6
    #13 0x7f244d2e6b1e in testing::internal::UnitTestImpl::RunAllTests() /home/engshare/third-party2/googletest/1.11.0/src/googletest/googletest/src/gtest.cc:5855:47
    #14 0x7f244d2e5d87 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/engshare/third-party2/googletest/1.11.0/src/googletest/googletest/src/gtest.cc:2665:29
    #15 0x7f244d2e5d87 in testing::UnitTest::Run() /home/engshare/third-party2/googletest/1.11.0/src/googletest/googletest/src/gtest.cc:5438:55
    #16 0x7f244ef37ae0 in RUN_ALL_TESTS() third-party-buck/platform010/build/googletest/include/gtest/gtest.h:2490
    #17 0x7f244ef37758 in main common/gtest/LightMain.cpp:20
    #18 0x7f244a62c656 in __libc_start_call_main /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #19 0x7f244a62c717 in __libc_start_main_impl /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../csu/libc-start.c:409:3
    #20 0x56d660 in _start /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/x86_64/start.S:116

SUMMARY: UndefinedBehaviorSanitizer: invalid-null-argument velox/vector/DecodedVector.cpp:339:9 in
```

**Comment by mbasmanova** [comment]
Same root cause as #2975
