### ISSUE TITLE
Output buffers for task not found in TPCDS - Q54

### ISSUE THREAD

**Issue by uhyonc** [facebookincubator/velox#3009]
Hi,

I'm trying to track down the issue for the following error (in presto-native) while running Q54 (It also seems to happen for Q75 as well). It doesn't happen all the time, but quite frequently (can be reproed after a few tries)
`Exceptions.h:68] Line: ../../velox/velox/exec/PartitionedOutputBufferManager.cpp:481, Function:operator(), Expression: it != buffers.end() Output buffers for task not found: <taskId>, Source: RUNTIME, ErrorCode: INVALID_STATE`

The Exception itself seems to be happening on the table scan stage of `catalog_sales` (substage of JOIN of catalog_sales, web_sales, item) 

Here is the log entry on the host that is seeing this Exception:
```
16:15:29.683847 117152 PartitionedOutput.cpp:54] advance: 2, call flush dest=6
16:15:29.695827   202 TaskResource.cpp:177] abortResults: taskId=taskId...9.0.8, dest=9
16:15:29.696136   202 TaskManager.cpp:142] Task taskId...9.0.8, buffer 9, sequence 28 Results size: 0, page count: 0, complete: true
16:15:29.697368 117152 PartitionedOutput.cpp:283] getOutput: flushing blocked dest=5
16:15:29.699662 117152 PartitionedOutput.cpp:283] getOutput: flushing blocked dest=7
16:15:29.701635 117152 PartitionedOutput.cpp:283] getOutput: flushing blocked dest=8
16:15:29.703505 117152 PartitionedOutput.cpp:283] getOutput: flushing blocked dest=9
16:15:29.705298 117152 PartitionedOutput.cpp:283] getOutput: flushing blocked dest=10
16:15:29.707746 117152 PartitionedOutput.cpp:283] getOutput: flushing blocked dest=11
16:15:29.709378   195 TaskResource.cpp:177] abortResults: taskId=taskId....9.0.8, dest=2
16:15:29.710055   195 PartitionedOutputBufferManager.cpp:539] deleteResults: taskId=taskId...9.0.8 dest=2
16:15:29.710165 117152 Exceptions.h:68] Line: ../../velox/velox/exec/PartitionedOutputBufferManager.cpp:481, Function:operator(), Expression: it != buffers.end() Output buffers for task not found: taskId....9.0.8, Source: RUNTIME, ErrorCode: INVALID_STATE
```

It looks as if the abortResults calls from the parent stage (Stage 8) has caused the task not be removed... e.g. in the following code within PartitionedOutputBufferManager.cpp
```
  if (buffer && buffer->deleteResults(destination)) {
    VLOG(0) << "deleteResults: taskId=" << taskId << " dest=" << destination;
    buffers_.withLock([&](auto& buffers) { buffers.erase(taskId); });
  }
```
The thread that's getting the exception seems to be within the Driver:
Driver.runInternal -> PartitionOutput.getOutput, which calls Destination.flush() within the `if (blockedDestination)` code block.
Destination.flush() calls bufferManager.enqueue (at the end)... which calls getBuffers()
```
std::shared_ptr<PartitionedOutputBuffer>
PartitionedOutputBufferManager::getBuffer(const std::string& taskId) {
  return buffers_.withLock([&](auto& buffers) {
    auto it = buffers.find(taskId);
    VELOX_CHECK(
        it != buffers.end(), "Output buffers for task not found: {}", taskId);
    return it->second;
  });
}
```
And it fails here because the buffer with the taskId currently being processed was removed just prior.

I currently can't figure out why there's an abort of the task being called while the Driver for that task is still executing...

**Comment by uhyonc** [comment]
FYI, I've tried removing the check, returning nullptr and adding a check on the caller side.
Doing removes the query errors. Would this be a safe thing to do?

**Comment by mbasmanova** [comment]
> I currently can't figure out why there's an abort of the task being called while the Driver for that task is still executing...

One reason this may happen if the downstream task has failed or finished processing early (LIMIT N). Can you check whether this is happening? BTW, would you attache the distributed query plan, the output of EXPLAIN (TYPE DISTRIBUTED) <query>?

**Comment by mbasmanova** [comment]
It sounds like a race condition between upstream task enqueueing data via PartitionedOutputBufferManager::enqueue and downstream task or coordinator aborting the task via PartitionedOutputBufferManager::deleteResults.

We need to figure out how to handle this scenario.

There is logic in PartitionedOutputBuffer::enqueue to handle the case where one of the destinations called abort.

```
      if (auto buffer = buffers_[destination].get()) {
        buffer->enqueue(std::move(data));
        dataAvailableCallbacks.emplace_back(buffer->getAndClearNotify());
      } else {
        // Some downstream tasks may finish early and delete the
        // corresponding buffers. Further data for these buffers is dropped.
        totalSize_ -= data->size();
      }
```

We need to extend this logic to handle the case when all destinations called abort. Currently, after last destination called abort PartitionedOutputBufferManager::deleteResults removes task entry from the buffers_. One option is to keep that entry and delete it only in PartitionedOutputBufferManager::removeTask.

Let's start by adding a test to reproduce this issue. See velox/exec/tests/MultiFragmentTest.cpp

**Comment by uhyonc** [comment]
Hi, I'll see if I can start by adding a test case that will reproduce this issue in MultiFragmentTest.cpp.

**Comment by uhyonc** [comment]
[TPCDS_Q54_Explain.txt](https://github.com/facebookincubator/velox/files/9892526/TPCDS_Q54_Explain.txt)

**Comment by markjin1990** [comment]
It's because the parent stage finishes early due to Limit N as @mbasmanova mentioned.
> I currently can't figure out why there's an abort of the task being called while the Driver for that task is still executing...

**Comment by mbasmanova** [comment]
CC: @spershin

**Comment by uhyonc** [comment]
Hi, I've update the [PR#3014] to include a simple fix I mentioned before (for comparison purposes).
I'll try out @mbasmanova idea of not removing the task's buffer in deleteResults(), and letting it get removed in removeTask()   and get back to you.

**Comment by uhyonc** [comment]
I've added a fix [PR#3035], a one liner which fixes this issue, including a unit test. Please take a look. @mbasmanova 

I've tested it against Q54 as well as most other TPCDS queries (that currently work with Prestissimo) without issues.

**Comment by uhyonc** [comment]
Also, I've found that this fix also fixes the occasional hanging issue we saw in some TPC-DS queries (Q8, Q32, Q71, Q78).
Here is the reason for that.

The hanging occurs because when Task::removeDriver() is called, Task::terminate() isn't called to mark the task as being finished (even though it's actually finished)

* Task::terminate() doesn't get called is because allFinished is false.
* allFinished is false because Task::checkedIfFinishedLocked() returns false.
* Task::checkedIfFinishedLocked() returns false because Task.partitionedOutputConsumed_ is false
* partitionedOutputConsumed_ is false because Task::setAllOutputConsumed() isn't called.
* Task::setAllOutputConsumed() isn't called because PartitionedOutputBuffer::deleteResults() (which sets this flag) isn't called for all the results
* PartitionedOutputBuffer::deleteResults() isn't called for all the results
* PartitionedOutputBuffer::deleteResults() isn't called for all the results because the buffer for the task has been erased in * PartitionedOutputBufferManager::deleteResults()

Relevant code in 
```
void PartitionedOutputBufferManager::deleteResults(
    const std::string& taskId,
    int destination) {
  auto buffer = buffers_.withLock(
      [&](auto& buffers) -> std::shared_ptr<PartitionedOutputBuffer> {
        auto it = buffers.find(taskId);
        if (it == buffers.end()) {
          return nullptr;
        }
        return it->second;
      });
  if (!buffer) {
    VLOG(0) << "deleteResults: buffer is null; taskId=" << taskId << ", destination=" << destination;
  }
  if (buffer && buffer->deleteResults(destination)) { // <-- when we erase the buffer for the task, buffer is null, so we never call deleteResults
    buffers_.withLock([&](auto& buffers) { buffers.erase(taskId); });
  }
}
```

**Comment by karteekmurthys** [comment]
I still hit this in my test code:
https://github.com/prestodb/presto/actions/runs/3434870459/jobs/5726596765

```
Error:  com.facebook.presto.nativeworker.TestHiveQueriesUsingJSON.testDecimalArithmetic  Time elapsed: 2.875 s  <<< FAILURE!
java.lang.AssertionError: Expected exception message 'it != buffers.end() Output buffers for task not found: 20221110_092308_00064_fhhkb.0.0.0' to match '.*Decimal overflow.*' for query: SELECT n - m from (values (decimal'99999999999999999999999999999999999999', decimal'-1')) t(n,m)
	at org.testng.Assert.fail(Assert.java:98)
	at com.facebook.presto.tests.QueryAssertions.assertExceptionMessage(QueryAssertions.java:351)
	at com.facebook.presto.tests.QueryAssertions.assertQueryFails(QueryAssertions.java:332)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQueryFails(AbstractTestQueryFramework.java:251)
	at com.facebook.presto.nativeworker.TestHiveQueries.testDecimalArithmetic(TestHiveQueries.java:441)
	at com.facebook.presto.nativeworker.TestHiveQueriesUsingJSON.testDecimalArithmetic(TestHiveQueriesUsingJSON.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

Reproducible only on linux machines.

**Comment by karteekmurthys** [comment]
On adding some logs, it seems like in my case the bufferManager is accessed after the taskId entry in the map is removed due to the exception. Here is the sequence of events:

```
Buffer erased from Map by a driver:77540 TID ---> 08:17:14.898089 77540 PartitionedOutputBufferManager.cpp:667] Buffer erased by PID: 77502, TID: 77540
08:17:14.898521 77542 TaskManager.cpp:258] Processing pending result request for task 20221119_081714_00007_ibfum.0.0.0, buffer 0, sequence 0
Buffer looked up in map by another driver: 77542 TID ---> 08:17:14.898542 77542 Exceptions.h:68] Line: ../../velox/velox/exec/PartitionedOutputBufferManager.cpp:553, Function:operator(), Expression: it != buffers.end() Output buffers for task not found: 20221119_081714_00007_ibfum.0.0.0 PID:77502 TID:77542, Source: RUNTIME, ErrorCode: INVALID_STATE
```

**Comment by karteekmurthys** [comment]
Possible solutions:

The exception throw in getBuffers is not handled currently. The point at which we know info about the Task is  down the stack is TaskManager::createOrUpdateTask().

We can catch the exception here and check if the Task is already FAILED/ABORTED.
If the task hasn't failed yet, throw the exception or 
```
try {
        getData(
                resultRequest->promise.lock(),
                resultRequest->taskId,
                resultRequest->bufferId,
                resultRequest->token,
                resultRequest->maxSize,
                *bufferManager_);

    } catch (const std::exception& e) {
       VLOG(1) << "TaskManager::createOrUpdateTask getData failed " << e.what() ;
        if (prestoTask->info.taskStatus.state == protocol::TaskState::ABORTED
        || prestoTask->info.taskStatus.state == protocol::TaskState::FAILED) {
            // Task is already aborted/failed. Nothing to do.
            return std::make_unique<TaskInfo>(prestoTask->updateInfoLocked());
        }
       throw e;
    }
```
Please let me know if you have any suggestions.
@mbasmanova @majetideepak @aditi-pandit
