### ISSUE TITLE
Signed integer overflow in Timestamp.h:52

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#3038]
```
I0922 16:15:19.207865  6704 ExpressionFuzzer.cpp:651] ==============================> Started iteration 9902 (seed: 1470783890)
I0922 16:15:19.214931  6704 ExpressionFuzzer.cpp:544] Executing expression: date_add(url_extract_path(format_datetime("2090-01-03T13:25:59.952422179",url_encode(date_format(from_unixtime(ln(negate(floor(0.3070260350791145)))),"k4v8Etn3V3N661TUVA4iKjyR6AVEo")))),strpos("tsUVo2Emb7811M1ckAu75D0bm01xw4aU8YcOkqjimUT0Jk2F",regexp_extract("c0","c1",1001200499),quarter("1946725-03-22")),date_trunc("nMyk4v2aH84Ir5TUeRE25","1853336-03-20"))
I0922 16:15:19.215145  6704 ExpressionFuzzer.cpp:547] 2 vectors as input:
I0922 16:15:19.215154  6704 ExpressionFuzzer.cpp:549] 	[FLAT VARCHAR: 100 elements, 7 nulls]
I0922 16:15:19.215175  6704 ExpressionFuzzer.cpp:549] 	[DICTIONARY VARCHAR: 100 elements, 10 nulls], [FLAT VARCHAR: 100 elements, 6 nulls]
buck-out/v2/gen/fbcode/4b41d6efb851df45/velox/type/__velox_timestamp__/headers/velox/type/Timestamp.h:52:21: runtime error: signed integer overflow: -9223372036854776 * 1000 cannot be represented in type 'long'
    #0 0x7fa9e79d4057 in facebook::velox::Timestamp::toMillis() const buck-out/v2/gen/fbcode/4b41d6efb851df45/velox/type/__velox_timestamp__/headers/velox/type/Timestamp.h:52
    #1 0x7fa9e79d0d65 in facebook::velox::functions::DateTimeFormatter::format[abi:cxx11](facebook::velox::Timestamp const&, date::time_zone const*) const fbcode/velox/functions/lib/DateTimeFormatter.cpp:905
...
```

**Comment by bikramSingh91** [comment]
@kagamiori Is there more work left or can we close this?

**Comment by mbasmanova** [comment]
@kagamiori Is this fixed now?

**Comment by kagamiori** [comment]
> @kagamiori Is this fixed now?

> @kagamiori Is there more work left or can we close this?

Yes. Closing this issue since it's fixed.
