### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow in ArrayVector::ensureWritable

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#3043]
Repro files:

[ensure-writable.tar.gz](https://github.com/facebookincubator/velox/files/9906042/ensure-writable.tar.gz)

```
I1031 18:38:27.293980 1411243 ExpressionFuzzer.cpp:702] ==============================> Started iteration 2914 (seed: 2691273178)
I1031 18:38:27.314316 1411243 ExpressionVerifier.cpp:141] Executing expression: element_at(map_keys(10 elements starting at 230 {[230->242] 0.3601336727617367 => null, [231->260] 0.459348
99953351493 => 0.21591263486798984, [232->34] 0.0653445561079884 => 0.26649579510719434, [233->127] 0.591986389610133 => 0.48361826967107957, [234->165] 0.9683726506723835 => 0.5094288146
431503, ...}),subscript(array_except(slice(10 elements starting at 110 {-1483749992, 137271111, -573618374, 1224438244, 606963587, ...},null,bitwise_arithmetic_shift_right("c0",subscript(
map(slice(10 elements starting at 10 {-12, -88, 102, 96, 69, ...},array_position("c1",round(0.6287888288497925,-1812485408),year_of_week("c2")),"c3"),"c4"),15))),"c5"),month(date_add(elem
ent_at(10 elements starting at 110 {[110->267] -1328883188 -12:-2:-9.-216 => Df*S._S.I[z'%&)S#@2&Wfx|j6(87><;v, [111->153] 1462034578 09:49:06.836 => TOj()6ld>\#RRyXl0*RUOFvM*d?'`/{PN7g5F
5iEk>oFEQdp^VZ7V}~{<ego, [112->217] -1790022098 22:43:00.063 => n2Pi(L3|kvaN/]8Un]Wm]s4Q!wd@"F3xq(,8?M%pL6')R.rx~Wu4$?c, [113->288] -1443039913 07:36:39.574 => hY0}Y~|-:!_e3@oH$4w2xa,X1[D
+dGm?h4XVF\xp33/|EuKxP;B"fQ>_@WNzHHEWCnN4t#t;?';AWr6joGB{$vDMp=5`Cg-BB, [114->259] -2013674195 -5:-20:00.-352 => null, ...},element_at(1 elements starting at 350 {0.3908015990101299 => nu
ll},"c6")),"c7",subscript(1 elements starting at 440 {-1129605487 => [440->448] 3393632-12-22},subscript(1 elements starting at 290 {7544 => 1707793329},"c8"))))))
I1031 18:38:27.314893 1411243 ExpressionVerifier.cpp:144] 9 vectors as input:
I1031 18:38:27.314906 1411243 ExpressionVerifier.cpp:146]       [DICTIONARY INTEGER: 100 elements, 13 nulls], [FLAT INTEGER: 100 elements, 11 nulls]
I1031 18:38:27.314941 1411243 ExpressionVerifier.cpp:146]       [DICTIONARY ARRAY<REAL>: 100 elements, 12 nulls], [ARRAY ARRAY<REAL>: 100 elements, 12 nulls]
I1031 18:38:27.314977 1411243 ExpressionVerifier.cpp:146]       [DICTIONARY TIMESTAMP: 100 elements, 7 nulls], [FLAT TIMESTAMP: 100 elements, 7 nulls]
I1031 18:38:27.315001 1411243 ExpressionVerifier.cpp:146]       [DICTIONARY BIGINT: 100 elements, 10 nulls], [DICTIONARY BIGINT: 100 elements, 8 nulls], [DICTIONARY BIGINT: 100 elements,
8 nulls], [DICTIONARY BIGINT: 100 elements, 9 nulls], [DICTIONARY BIGINT: 100 elements, 8 nulls], [FLAT BIGINT: 100 elements, 12 nulls]
I1031 18:38:27.315068 1411243 ExpressionVerifier.cpp:146]       [DICTIONARY ARRAY<INTEGER>: 100 elements, 12 nulls], [DICTIONARY ARRAY<INTEGER>: 100 elements, 13 nulls], [ARRAY ARRAY<INTE
GER>: 100 elements, 15 nulls]
I1031 18:38:27.315104 1411243 ExpressionVerifier.cpp:146]       [ARRAY ARRAY<INTEGER>: 100 elements, 11 nulls]
I1031 18:38:27.315121 1411243 ExpressionVerifier.cpp:146]       [FLAT DOUBLE: 100 elements, 9 nulls]
I1031 18:38:27.315137 1411243 ExpressionVerifier.cpp:146]       [DICTIONARY BIGINT: 100 elements, 16 nulls], [DICTIONARY BIGINT: 100 elements, 10 nulls], [FLAT BIGINT: 100 elements, 13 nu
lls]
I1031 18:38:27.315168 1411243 ExpressionVerifier.cpp:146]       [DICTIONARY SMALLINT: 100 elements, 3 nulls], [DICTIONARY SMALLINT: 100 elements, 12 nulls], [FLAT SMALLINT: 100 elements,
10 nulls]
=================================================================
==1411243==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x611000684480 at pc 0x00000037f222 bp 0x7ffea0ec75f0 sp 0x7ffea0ec6da0
READ of size 400 at 0x611000684480 thread T0
SCARINESS: 26 (multi-byte-read-heap-buffer-overflow)
    #0 0x37f221 in __asan_memcpy (/data/users/mbasmanova/fbsource/fbcode/buck-out/dev/gen/aab7ed39/velox/expression/tests/velox_expression_fuzzer_test+0x37f221)
    #1 0x7f66a3c680e1 in facebook::velox::ArrayVector::ensureWritable(facebook::velox::SelectivityVector const&) velox/vector/ComplexVector.cpp:620
    #2 0x7f66a3456356 in facebook::velox::BaseVector::ensureWritable(facebook::velox::SelectivityVector const&, std::shared_ptr<facebook::velox::Type const> const&, facebook::velox::memor
y::MemoryPool*, std::shared_ptr<facebook::velox::BaseVector>&, facebook::velox::VectorPool*) velox/vector/BaseVector.cpp:576
    #3 0x7f66a4a9fa7d in facebook::velox::exec::Expr::addNulls(facebook::velox::SelectivityVector const&, unsigned long const*, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::
velox::Type const> const&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:945
    #4 0x7f66a4a92e24 in facebook::velox::exec::Expr::addNulls(facebook::velox::SelectivityVector const&, unsigned long const*, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::
velox::BaseVector>&) velox/expression/Expr.cpp:961
    #5 0x7f66a4a92baa in facebook::velox::exec::Expr::evalSimplifiedImpl(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseV
ector>&) velox/expression/Expr.cpp:318
    #6 0x7f66a4a9152f in facebook::velox::exec::Expr::evalSimplified(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVecto
r>&) velox/expression/Expr.cpp:259
    #7 0x7f66a4a924ea in facebook::velox::exec::Expr::evalSimplifiedImpl(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseV
ector>&) velox/expression/Expr.cpp:286
    #8 0x7f66a4a9152f in facebook::velox::exec::Expr::evalSimplified(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVecto
r>&) velox/expression/Expr.cpp:259
    #9 0x7f66a4aa6e57 in facebook::velox::exec::ExprSetSimplified::eval(int, int, bool, facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::vector<std::shared
_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&) velox/expression/Expr.cpp:1670
    #10 0x7f66a55e77c5 in facebook::velox::exec::ExprSetSimplified::eval(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::vector<std::shared_ptr<facebook::
velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&) velox/expression/Expr.h:562
    #11 0x7f66a55e4928 in facebook::velox::test::ExpressionVerifier::verify(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, std::shared_ptr<facebook::velox::RowVector> co
nst&, std::shared_ptr<facebook::velox::BaseVector>&&, bool) velox/expression/tests/ExpressionVerifier.cpp:218
    #12 0x7f66a9746516 in facebook::velox::test::ExpressionFuzzer::go() velox/expression/tests/ExpressionFuzzer.cpp:725
```

**Comment by mbasmanova** [comment]
Simple repro:

```
TEST_F(VectorTest, repro) {
  auto offsets = makeIndices(50, [](auto row) { return 0; });
  VectorPtr arrayVector = std::make_shared<ArrayVector>(
      pool_.get(),
      ARRAY(BIGINT()),
      makeNulls(100, [](auto row) { return row > 50; }),
      100,
      offsets,
      makeIndices(50, [](auto row) { return 0; }),
      makeFlatVector<int64_t>({1, 2, 3}));

  SelectivityVector rows(200);
  BaseVector::ensureWritable(rows, ARRAY(BIGINT()), pool_.get(), arrayVector);
}
```

**Comment by mbasmanova** [comment]
Repro using map_keys or map_values functions:

```
TEST_F(ExprTest, repro) {
  auto offsets = makeIndices(50, [](auto row) { return 0; });
  auto sizes = makeIndices(50, [](auto row) { return 0; });
  VectorPtr mapVector = std::make_shared<MapVector>(
      pool_.get(),
      MAP(BIGINT(), BIGINT()),
      makeNulls(100, [](auto row) { return row > 50; }),
      100,
      offsets,
      sizes,
      makeFlatVector<int64_t>({1, 2, 3}),
      makeFlatVector<int64_t>({10, 20, 30}));

  evaluate("map_keys(c0)", makeRowVector({mapVector}));
  evaluate("map_values(c0)", makeRowVector({mapVector}));
}
```

Workaround / fix:

```
diff --git a/fbcode/velox/functions/prestosql/MapKeysAndValues.cpp b/fbcode/velox/functions/prestosql/MapKeysAndValues.cpp
--- a/fbcode/velox/functions/prestosql/MapKeysAndValues.cpp
+++ b/fbcode/velox/functions/prestosql/MapKeysAndValues.cpp
@@ -82,7 +82,7 @@
         context.pool(),
         ARRAY(mapKeys->type()),
         mapVector->nulls(),
-        rows.size(),
+        rows.end(),
         mapVector->offsets(),
         mapVector->sizes(),
         mapKeys,
@@ -119,7 +119,7 @@
         context.pool(),
         ARRAY(mapValues->type()),
         mapVector->nulls(),
-        rows.size(),
+        rows.end(),
         mapVector->offsets(),
         mapVector->sizes(),
         mapValues,
```

**Comment by mbasmanova** [comment]
I think ArrayVector and MapVector need to check that offsets and sizes buffers are at least BaseVector::length_ * sizeof(vector_size_t) bytes long. Then, map_keys and map_values functions should create vectors of size rows.end() not rows.size().
