### ISSUE TITLE
UndefinedBehaviorSanitizer: signed-integer-overflow in Spark's remainder() function

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#3951]
### Description

Spark fuzzer test caught a runtime error because of the division during (-2147483648 % -1) at line 54 cannot be represented in int. 
https://github.com/facebookincubator/velox/blob/44a8b0071adab05c745fe85f1e890960647b10a2/velox/functions/sparksql/Arithmetic.h#L46-L57

### Error Reproduction

This error can be reproduced internally by checking out 63393c8c3 and then running velox/expression/tests/spark_expression_fuzzer_test --seed 1395955578.

To reproduce it externally, it should be easy to write a unit test for the remainder function with the inputs given above.

### Relevant logs

```bash
I0206 11:41:49.708652 3633660 ExpressionFuzzer.cpp:976] ==============================> Started iteration 0 (seed: 1395955578)
I0206 11:41:49.716131 3633660 ExpressionVerifier.cpp:88] Executing expression: remainder(shiftleft("c0",1132446686),unaryminus(shiftright(abs(abs(length(lower(<jXc=e=@z;v2Mv-u)))),round("c1","c2"))))
I0206 11:41:49.716550 3633660 ExpressionVerifier.cpp:31] 3 vectors as input:
I0206 11:41:49.716621 3633660 ExpressionVerifier.cpp:33] 	[DICTIONARY INTEGER: 100 elements, 7 nulls], [FLAT INTEGER: 100 elements, 13 nulls]
I0206 11:41:49.716728 3633660 ExpressionVerifier.cpp:33] 	[DICTIONARY INTEGER: 100 elements, 7 nulls], [FLAT INTEGER: 100 elements, 16 nulls]
I0206 11:41:49.716799 3633660 ExpressionVerifier.cpp:33] 	[DICTIONARY INTEGER: 100 elements, 12 nulls], [FLAT INTEGER: 100 elements, 9 nulls]
buck-out/dev/gen/aab7ed39/velox/functions/sparksql/velox_functions_spark#header-mode-symlink-tree-with-header-map,headers/velox/functions/sparksql/Arithmetic.h:54:16: runtime error: division of -2147483648 by -1 cannot be represented in type 'int'
    #0 0x7fd009c4264a in void facebook::velox::bits::forEachBit<void facebook::velox::exec::EvalCtx::applyToSelectedNoThrow<void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::iterate<facebook::velox::exec::VectorReader<int>, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, facebook::velox::exec::VectorReader<int>&, facebook::velox::exec::VectorReader<int>&) const::'lambda1'(auto)>(facebook::velox::SelectivityVector const&, auto)::'lambda'(auto)>(unsigned long const*, int, int, bool, auto)::'lambda'(int, unsigned long)::operator()(int, unsigned long) const velox/functions/sparksql/Arithmetic.h:54
    #1 0x7fd009c419d8 in void facebook::velox::bits::forEachWord<void facebook::velox::bits::forEachBit<void facebook::velox::exec::EvalCtx::applyToSelectedNoThrow<void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::iterate<facebook::velox::exec::VectorReader<int>, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, facebook::velox::exec::VectorReader<int>&, facebook::velox::exec::VectorReader<int>&) const::'lambda1'(auto)>(facebook::velox::SelectivityVector const&, auto)::'lambda'(auto)>(unsigned long const*, int, int, bool, auto)::'lambda'(int, unsigned long), void facebook::velox::bits::forEachBit<void facebook::velox::exec::EvalCtx::applyToSelectedNoThrow<void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::iterate<facebook::velox::exec::VectorReader<int>, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, facebook::velox::exec::VectorReader<int>&, facebook::velox::exec::VectorReader<int>&) const::'lambda1'(auto)>(facebook::velox::SelectivityVector const&, auto)::'lambda'(auto)>(unsigned long const*, int, int, bool, auto)::'lambda'(int)>(int, int, auto, void facebook::velox::bits::forEachBit<void facebook::velox::exec::EvalCtx::applyToSelectedNoThrow<void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::iterate<facebook::velox::exec::VectorReader<int>, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, facebook::velox::exec::VectorReader<int>&, facebook::velox::exec::VectorReader<int>&) const::'lambda1'(auto)>(facebook::velox::SelectivityVector const&, auto)::'lambda'(auto)>(unsigned long const*, int, int, bool, auto)::'lambda'(int)) velox/common/base/BitUtil.h:190
    #2 0x7fd009c415ce in void facebook::velox::bits::forEachBit<void facebook::velox::exec::EvalCtx::applyToSelectedNoThrow<void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::iterate<facebook::velox::exec::VectorReader<int>, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, facebook::velox::exec::VectorReader<int>&, facebook::velox::exec::VectorReader<int>&) const::'lambda1'(auto)>(facebook::velox::SelectivityVector const&, auto)::'lambda'(auto)>(unsigned long const*, int, int, bool, auto) velox/common/base/BitUtil.h:402
    #3 0x7fd009c4106f in void facebook::velox::bits::forEachSetBit<void facebook::velox::exec::EvalCtx::applyToSelectedNoThrow<void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::iterate<facebook::velox::exec::VectorReader<int>, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, facebook::velox::exec::VectorReader<int>&, facebook::velox::exec::VectorReader<int>&) const::'lambda1'(auto)>(facebook::velox::SelectivityVector const&, auto)::'lambda'(auto)>(unsigned long const*, int, int, auto) velox/common/base/BitUtil.h:436
    #4 0x7fd009c40dbb in void facebook::velox::SelectivityVector::applyToSelected<void facebook::velox::exec::EvalCtx::applyToSelectedNoThrow<void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::iterate<facebook::velox::exec::VectorReader<int>, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, facebook::velox::exec::VectorReader<int>&, facebook::velox::exec::VectorReader<int>&) const::'lambda1'(auto)>(facebook::velox::SelectivityVector const&, auto)::'lambda'(auto)>(auto) const velox/vector/SelectivityVector.h:436
    #5 0x7fd009c3fcd3 in void facebook::velox::exec::EvalCtx::applyToSelectedNoThrow<void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::iterate<facebook::velox::exec::VectorReader<int>, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, facebook::velox::exec::VectorReader<int>&, facebook::velox::exec::VectorReader<int>&) const::'lambda1'(auto)>(facebook::velox::SelectivityVector const&, auto) velox/expression/EvalCtx.h:95
    #6 0x7fd009c372d8 in void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext::applyToSelectedNoThrow<void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::iterate<facebook::velox::exec::VectorReader<int>, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, facebook::velox::exec::VectorReader<int>&, facebook::velox::exec::VectorReader<int>&) const::'lambda1'(auto)>(auto) velox/expression/SimpleFunctionAdapter.h:190
    #7 0x7fd009c36822 in void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::iterate<facebook::velox::exec::VectorReader<int>, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, facebook::velox::exec::VectorReader<int>&, facebook::velox::exec::VectorReader<int>&) const velox/expression/SimpleFunctionAdapter.h:616
    #8 0x7fd009c35de4 in void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::unpack<2, false, facebook::velox::exec::VectorReader<int>, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, std::vector<std::optional<facebook::velox::exec::LocalDecodedVector>, std::allocator<std::optional<facebook::velox::exec::LocalDecodedVector> > >&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > > const&, facebook::velox::exec::VectorReader<int>&, facebook::velox::exec::VectorReader<int>&) const velox/expression/SimpleFunctionAdapter.h:482
    #9 0x7fd009c35ca9 in void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::unpack<1, false, facebook::velox::exec::VectorReader<int> >(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, std::vector<std::optional<facebook::velox::exec::LocalDecodedVector>, std::allocator<std::optional<facebook::velox::exec::LocalDecodedVector> > >&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > > const&, facebook::velox::exec::VectorReader<int>&) const velox/expression/SimpleFunctionAdapter.h:519
    #10 0x7fd009be4588 in void facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::unpack<0, false>(facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::ApplyContext&, std::vector<std::optional<facebook::velox::exec::LocalDecodedVector>, std::allocator<std::optional<facebook::velox::exec::LocalDecodedVector> > >&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > > const&) const velox/expression/SimpleFunctionAdapter.h:519
    #11 0x7fd009be28c7 in facebook::velox::exec::SimpleFunctionAdapter<facebook::velox::core::UDFHolder<facebook::velox::functions::sparksql::RemainderFunction<facebook::velox::exec::VectorExec>, facebook::velox::exec::VectorExec, int, int, int> >::apply(facebook::velox::SelectivityVector const&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&, std::shared_ptr<facebook::velox::Type const> const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) const velox/expression/SimpleFunctionAdapter.h:353
    #12 0x7fd002ebb8ce in facebook::velox::exec::Expr::applyFunction(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1495
    #13 0x7fd002ebe94a in facebook::velox::exec::Expr::evalAll(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1324
    #14 0x7fd002ec554c in facebook::velox::exec::Expr::evalWithNulls(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:1033
    #15 0x7fd002ebffa8 in facebook::velox::exec::Expr::evalEncodings(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) velox/expression/Expr.cpp:923
    #16 0x7fd002ebd21b in facebook::velox::exec::Expr::eval(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&, bool) velox/expression/Expr.cpp:602
    #17 0x7fd002ecd91f in facebook::velox::exec::ExprSet::eval(int, int, bool, facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&) velox/expression/Expr.cpp:1739
    #18 0x7fd005303185 in facebook::velox::exec::ExprSet::eval(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > >&) velox/expression/Expr.h:487
    #19 0x7fd0052ff985 in facebook::velox::test::ExpressionVerifier::verify(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, std::shared_ptr<facebook::velox::RowVector> const&, std::shared_ptr<facebook::velox::BaseVector>&&, bool, std::vector<unsigned int, std::allocator<unsigned int> >) velox/expression/tests/ExpressionVerifier.cpp:146
    #20 0x7fd00cb6b680 in facebook::velox::test::ExpressionFuzzer::go() velox/expression/tests/ExpressionFuzzer.cpp:1021
    #21 0x7fd00cbb7056 in facebook::velox::test::expressionFuzzer(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<facebook::velox::exec::FunctionSignature const*, std::allocator<facebook::velox::exec::FunctionSignature const*> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<facebook::velox::exec::FunctionSignature const*, std::allocator<facebook::velox::exec::FunctionSignature const*> > > > >, unsigned long) velox/expression/tests/ExpressionFuzzer.cpp:1074
    #22 0x2e6dcf in FuzzerRunner::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) velox/expression/tests/FuzzerRunner.h:140
    #23 0x2e6570 in main velox/expression/tests/SparkExpressionFuzzerTest.cpp:61
    #24 0x7fd00322c656 in __libc_start_call_main /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #25 0x7fd00322c717 in __libc_start_main_impl /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../csu/libc-start.c:409:3
    #26 0x2c5d70 in _start /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/x86_64/start.S:116

SUMMARY: UndefinedBehaviorSanitizer: signed-integer-overflow buck-out/dev/gen/aab7ed39/velox/functions/sparksql/velox_functions_spark#header-mode-symlink-tree-with-header-map,headers/velox/functions/sparksql/Arithmetic.h:54:16 in
```

**Comment by mbasmanova** [comment]
CC: @zhejiangxiaomai @rui-mo

**Comment by mbasmanova** [comment]
@zhejiangxiaomai @rui-mo Rui, could someone from Gluten team help look into this?

**Comment by rui-mo** [comment]
> @zhejiangxiaomai @rui-mo Rui, could someone from Gluten team help look into this?

@mbasmanova Yes, I can look into this issue. This error occurs due to `2147483647` is the largest positive number of int. Should we return false for this case? And we can also support int64 as the output type.

**Comment by rui-mo** [comment]
> @rui-mo Let's check what does Spark return for this case and make sure our implementation matches.

@mbasmanova Spark returns 0 for this case. Opened above PR to fix this issue.
