### ISSUE TITLE
HDFS register issue: Where should I add the two configs hive.hdfs.host and hive.hdfs.port ?

### ISSUE THREAD

**Issue by GuChangyang** [facebookincubator/velox#4363]
### Problem description

I am using hdfs as connector.
After I added hive.hdfs.host and hive.hdfs.port in core-site.xml and hdfs-site.xml, 
The below code still return null to me: https://github.com/facebookincubator/velox/blob/main/velox/connectors/hive/storage_adapters/hdfs/HdfsFileSystem.cpp#L51

So what the correct path that I should add the two configs: 
hive.hdfs.port and hive.hdfs.port.

thank you

### System information

I am on debian 10

**Comment by mbasmanova** [comment]
CC: @majetideepak @shiyu-bytedance

**Comment by majetideepak** [comment]
@GuChangyang can you add them to the `hive.properties` config file and try?

**Comment by GuChangyang** [comment]
@majetideepak After adding the two configs in  hive.properties, I can not start coordinator and got below errors;

```
2023-03-23T05:11:05.938+0800    ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Configuration property 'hive.hdfs.host' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

2) Configuration property 'hive.hdfs.port' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

2 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'hive.hdfs.host' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

2) Configuration property 'hive.hdfs.port' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
        at com.facebook.presto.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:139)
        at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:388)
        at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:235)
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:227)
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:213)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:123)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:98)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:80)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:151)
```

**Comment by GuChangyang** [comment]
It works after adding in worker's hive.properties,
