### ISSUE TITLE
SIGSEGV Aws::Utils::Crypto::CleanupCrypto

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#4562]
### Bug description

A segfault is seen when the program terminates. This is likely due to the s3fs instance being a static variable.
This is discouraged. See https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/basic-use.html
``
To avoid memory issues caused by the nondeterministic order of static variable destruction, do not wrap the calls to Aws::InitAPI and Aws::ShutdownAPI into another static object.
``
https://github.com/aws/aws-sdk-cpp/issues/1550

### System information

Velox System Info v0.0.2
Commit: f51160d7c75c7ac213e59eee200ed4f5d25423bf
CMake Version: 3.25.1
System: Linux-6.1.19-30.43.amzn2023.x86_64
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.3.1
C Compiler: /usr/bin/cc
C Compiler Version: 11.3.1
CMake Prefix Path: /usr/local;/usr;/;/usr/local;/usr/local;/usr/X11R6;/usr/pkg;/opt

### Relevant logs

```bash
#0  0x000000000b8e4561 in Aws::Utils::Crypto::CleanupCrypto() ()
#1  0x000000000b8aaeb2 in Aws::ShutdownAPI(Aws::SDKOptions const&) ()
#2  0x000000000b70fd46 in facebook::velox::filesystems::S3FileSystem::Impl::~Impl (this=0x12893c60, __in_chrg=<optimized out>)
    at /home/ec2-user/velox/velox/connectors/hive/storage_adapters/s3fs/S3FileSystem.cpp:315
#3  0x000000000b719ec6 in __gnu_cxx::new_allocator<facebook::velox::filesystems::S3FileSystem::Impl>::destroy<facebook::velox::filesystems::S3FileSystem::Impl> (this=0x12893c60, 
    __p=0x12893c60) at /usr/include/c++/11/ext/new_allocator.h:168
#4  0x000000000b719cd1 in std::allocator_traits<std::allocator<facebook::velox::filesystems::S3FileSystem::Impl> >::destroy<facebook::velox::filesystems::S3FileSystem::Impl> (__a=..., 
    __p=0x12893c60) at /usr/include/c++/11/bits/alloc_traits.h:535
#5  0x000000000b7193cd in std::_Sp_counted_ptr_inplace<facebook::velox::filesystems::S3FileSystem::Impl, std::allocator<facebook::velox::filesystems::S3FileSystem::Impl>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x12893c50) at /usr/include/c++/11/bits/shared_ptr_base.h:528
#6  0x00000000064c7da8 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x12893c50) at /usr/include/c++/11/bits/shared_ptr_base.h:168
#7  0x00000000064c415b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x12896ca0, __in_chrg=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:705
#8  0x000000000b7104fe in std::__shared_ptr<facebook::velox::filesystems::S3FileSystem::Impl, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x12896c98, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#9  0x000000000b71051a in std::shared_ptr<facebook::velox::filesystems::S3FileSystem::Impl>::~shared_ptr (this=0x12896c98, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr.h:122
#10 0x000000000b718868 in facebook::velox::filesystems::S3FileSystem::~S3FileSystem (this=0x12896c80, __in_chrg=<optimized out>)
    at /home/ec2-user/velox/./velox/connectors/hive/storage_adapters/s3fs/S3FileSystem.h:27
#11 0x000000000b719e99 in __gnu_cxx::new_allocator<facebook::velox::filesystems::S3FileSystem>::destroy<facebook::velox::filesystems::S3FileSystem> (this=0x12896c80, __p=0x12896c80)
    at /usr/include/c++/11/ext/new_allocator.h:168
#12 0x000000000b719c91 in std::allocator_traits<std::allocator<facebook::velox::filesystems::S3FileSystem> >::destroy<facebook::velox::filesystems::S3FileSystem> (__a=..., __p=0x12896c80)
    at /usr/include/c++/11/bits/alloc_traits.h:535
#13 0x000000000b719257 in std::_Sp_counted_ptr_inplace<facebook::velox::filesystems::S3FileSystem, std::allocator<facebook::velox::filesystems::S3FileSystem>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x12896c70) at /usr/include/c++/11/bits/shared_ptr_base.h:528
#14 0x00000000064c7da8 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x12896c70) at /usr/include/c++/11/bits/shared_ptr_base.h:168
#15 0x00000000064c415b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x126e6218 <facebook::velox::filesystems::s3fs+8>, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr_base.h:705
#16 0x00000000064df6e4 in std::__shared_ptr<facebook::velox::filesystems::FileSystem, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x126e6210 <facebook::velox::filesystems::s3fs>, 
    __in_chrg=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#17 0x00000000064df700 in std::shared_ptr<facebook::velox::filesystems::FileSystem>::~shared_ptr (this=0x126e6210 <facebook::velox::filesystems::s3fs>, __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr.h:122
#18 0x00007ffff70574b5 in __run_exit_handlers () from /lib64/libc.so.6
#19 0x00007ffff7057630 in exit () from /lib64/libc.so.6
#20 0x00007ffff703feb7 in __libc_start_call_main () from /lib64/libc.so.6
#21 0x00007ffff703ff60 in __libc_start_main_impl () from /lib64/libc.so.6
#22 0x00000000064af0b5 in _start ()
```

**Comment by majetideepak** [comment]
Fixed
