### ISSUE TITLE
Left/Right Join without join criteria must be implemented as NestedLoopJoin

### ISSUE THREAD

**Issue by karteekmurthys** [facebookincubator/velox#5715]
### Bug description

Repro steps:
```
presto:kart> select * from t1 left join t6 on t1.c0=2;

WARNING: line 1:39: JOIN ON condition(s) do not reference the joined table 't6' and other tables in the same expression that can cause performance issues as it may lead to a cross join with filter

Query 20230718_234102_00030_fktn2, FAILED, 1 node
Splits: 2 total, 1 done (50.00%)
[Latency: client-side: 0:01, server-side: 432ms] [3 rows, 410B] [6 rows/s, 949B/s]

Query 20230718_234102_00030_fktn2 failed: !leftKeys_.empty() JoinNode requires at least one join key
presto:kart> describe t1;
 Column |  Type   | Extra | Comment 
--------+---------+-------+---------
 c0     | integer |       |         
(1 row)

Query 20230718_233943_00027_fktn2, FINISHED, 2 nodes
Splits: 3 total, 3 done (100.00%)
[Latency: client-side: 0:01, server-side: 0:01] [1 rows, 54B] [1 rows/s, 82B/s]

presto:kart> describe t6;
 Column |  Type   | Extra | Comment 
--------+---------+-------+---------
 c0     | integer |       |         
(1 row)
```

` !leftKeys_.empty() JoinNode requires at least one join key` this exception occurs while creating a HashJoinNode and there is no criteria is empty.

This issue occurred while trying to port the following Presto Java test to native:

```
  @Test
    public void testDoubleFilteredLeftJoinWithRightConstantEquality()
    {
        assertQuery("SELECT COUNT(*) FROM (SELECT * FROM lineitem WHERE orderkey % 1024 = 0) lineitem LEFT JOIN (SELECT * FROM orders WHERE orderkey % 1024 = 0) orders ON orders.orderkey = 1024");
    }
```
Today, only inner-join without criteria and a filter is implemented as NestedLoopJoin. The conditions must also include Left/Right join without criteria but with filters.
Relevant code:
```
core::PlanNodePtr VeloxQueryPlanConverterBase::toVeloxQueryPlan(
    const std::shared_ptr<const protocol::JoinNode>& node,
    const std::shared_ptr<protocol::TableWriteInfo>& tableWriteInfo,
    const protocol::TaskId& taskId) {
  auto joinType = toJoinType(node->type);
  if (node->criteria.empty() && core::isInnerJoin(joinType) && !node->filter) {
    return std::make_shared<core::NestedLoopJoinNode>(
        node->id,
        toVeloxQueryPlan(node->left, tableWriteInfo, taskId),
        toVeloxQueryPlan(node->right, tableWriteInfo, taskId),
        toRowType(node->outputVariables));
  }
```
Thanks @aditi-pandit for helping with the triage.

### System information

N/A

**Comment by karteekmurthys** [comment]
cc: @majetideepak @mbasmanova

**Comment by mknegi** [comment]
@karteekmurthys - Would the following query fail due to this issue ?
```
SELECT o.orderkey, l.partkey, p.name FROM orders o LEFT JOIN lineitem l ON o.orderkey = l.orderkey LEFT JOIN part p ON l.partkey=p.partkey
```
Currently this query with join fails with the following stack:
```
Caused by: com.facebook.presto.sql.analyzer.SemanticException: Table hive.tpch.part does not exist
	at com.facebook.presto.util.MetadataUtils.getTableColumnMetadata(MetadataUtils.java:92)
	at com.facebook.presto.util.MetadataUtils.getTableColumnsMetadata(MetadataUtils.java:54)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1282)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:338)
	at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:1531)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:338)
	at com.facebook.presto.sql.tree.AliasedRelation.accept(AliasedRelation.java:71)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitJoin(StatementAnalyzer.java:1835)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitJoin(StatementAnalyzer.java:338)
	at com.facebook.presto.sql.tree.Join.accept(Join.java:90)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2596)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1615)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:338)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:138)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:360)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1116)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:338)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:105)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:330)
	at com.facebook.presto.sql.analyzer.Analyzer.analyzeSemantic(Analyzer.java:117)
	at com.facebook.presto.sql.analyzer.BuiltInQueryAnalyzer.analyze(BuiltInQueryAnalyzer.java:93)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:203)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:107)
	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:955)
	at com.facebook.presto.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:167)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
```

**Comment by mknegi** [comment]
> @karteekmurthys - Would the following query fail due to this issue ?
> 
> ```
> SELECT o.orderkey, l.partkey, p.name FROM orders o LEFT JOIN lineitem l ON o.orderkey = l.orderkey LEFT JOIN part p ON l.partkey=p.partkey
> ```
> 
> Currently this query with join fails with the following stack:
> 
> ```
> Caused by: com.facebook.presto.sql.analyzer.SemanticException: Table hive.tpch.part does not exist
> 	at com.facebook.presto.util.MetadataUtils.getTableColumnMetadata(MetadataUtils.java:92)
> 	at com.facebook.presto.util.MetadataUtils.getTableColumnsMetadata(MetadataUtils.java:54)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1282)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:338)
> 	at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
> 	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:1531)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:338)
> 	at com.facebook.presto.sql.tree.AliasedRelation.accept(AliasedRelation.java:71)
> 	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitJoin(StatementAnalyzer.java:1835)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitJoin(StatementAnalyzer.java:338)
> 	at com.facebook.presto.sql.tree.Join.accept(Join.java:90)
> 	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2596)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1615)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:338)
> 	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:138)
> 	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:360)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1116)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:338)
> 	at com.facebook.presto.sql.tree.Query.accept(Query.java:105)
> 	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
> 	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:330)
> 	at com.facebook.presto.sql.analyzer.Analyzer.analyzeSemantic(Analyzer.java:117)
> 	at com.facebook.presto.sql.analyzer.BuiltInQueryAnalyzer.analyze(BuiltInQueryAnalyzer.java:93)
> 	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:203)
> 	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:107)
> 	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:955)
> 	at com.facebook.presto.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:167)
> 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
> 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
> 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
> ```

I think the query that I pasted has a join key. Just wanted to double check it with you.

**Comment by mbasmanova** [comment]
CC: @usurai

**Comment by mknegi** [comment]
@mbasmanova - The issue that I was facing turned out to be env. The datafile for part table didn't exist in my env.
