### ISSUE TITLE
min_by aggregate function does not support complex types for the second parameter

### ISSUE THREAD

**Issue by mknegi** [facebookincubator/velox#5980]
### Description

It seems currently the min_by aggregate function does not support complex types for the second parameter.

This problem was discovered when running the following e2e testcase against velox:
**Testcase:** presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java::testMinBy()
https://github.com/prestodb/presto/blob/master/presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java#L1636

**Error reported:**
```
presto:tpch> SELECT MIN_BY(a, ROW(b, c)) FROM (VALUES (1, 2, 3), (2, 2, 1)) AS t(a, b, c);
Query 20230802_105550_00007_hbuu2 failed:  Unknown input types for presto.default.min_by (FINAL) aggregation: ROW<field0:INTEGER,field1:ROW<"":INTEGER,"":INTEGER>>
```

**Stack Trace**
```
java.lang.AssertionError: Execution of 'actual' query failed: SELECT MIN_BY(a, ROW(b, c)) FROM (VALUES (1, 2, 3), (2, 2, 1)) AS t(a, b, c)

	at org.testng.Assert.fail(Assert.java:98)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:178)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:157)
	at com.facebook.presto.tests.AbstractTestQueries.testMinBy(AbstractTestQueries.java:1616)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.lang.RuntimeException:  Unknown input types for presto.default.min_by (FINAL) aggregation: ROW<field0:INTEGER,field1:ROW<"":INTEGER,"":INTEGER>>
```

**Comment by yzhang1991** [comment]
We triaged this to be a Q2 item

**Comment by yzhang1991** [comment]
Hi @mknegi, can you retest and see if this can reproduce? Now we have this https://github.com/facebookincubator/velox/pull/6605 that maybe already fixed the issue.

**Comment by mknegi** [comment]
@yzhang1991 - Yes, this problem seems to be fixed now. Therefore, going ahead and closing this issue now.
