### ISSUE TITLE
avg_merge_extract_double: signed integer overflow

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6344]
### Bug description

This issue was discovered by running enhanced version of AggregationFuzzer: #6312

```
I0830 00:58:22.213734 3179618 AggregationFuzzer.cpp:246] Testing plan #3
I0830 00:58:22.213768 3179618 AggregationFuzzer.cpp:802] Executing query plan:
-- Aggregation[FINAL [g0, g1] a0 := avg_merge_extract_double("a0")] -> g0:TIMESTAMP, g1:INTEGER, a0:DOUBLE
  -- LocalPartition[REPARTITION HASH(g0, g1)] -> g0:TIMESTAMP, g1:INTEGER, a0:ROW<"":DOUBLE,"":BIGINT>
    -- Aggregation[PARTIAL [g0, g1] a0 := avg_merge_extract_double(ROW["c0"])] -> g0:TIMESTAMP, g1:INTEGER, a0:ROW<"":DOUBLE,"":BIGINT>
      -- Values[300 rows in 3 vectors] -> c0:ROW<field0:DOUBLE,field1:BIGINT>, g0:TIMESTAMP, g1:INTEGER
    -- Aggregation[PARTIAL [g0, g1] a0 := avg_merge_extract_double(ROW["c0"])] -> g0:TIMESTAMP, g1:INTEGER, a0:ROW<"":DOUBLE,"":BIGINT>
      -- Values[300 rows in 3 vectors] -> c0:ROW<field0:DOUBLE,field1:BIGINT>, g0:TIMESTAMP, g1:INTEGER
    -- Aggregation[PARTIAL [g0, g1] a0 := avg_merge_extract_double(ROW["c0"])] -> g0:TIMESTAMP, g1:INTEGER, a0:ROW<"":DOUBLE,"":BIGINT>
      -- Values[200 rows in 2 vectors] -> c0:ROW<field0:DOUBLE,field1:BIGINT>, g0:TIMESTAMP, g1:INTEGER
    -- Aggregation[PARTIAL [g0, g1] a0 := avg_merge_extract_double(ROW["c0"])] -> g0:TIMESTAMP, g1:INTEGER, a0:ROW<"":DOUBLE,"":BIGINT>
      -- Values[200 rows in 2 vectors] -> c0:ROW<field0:DOUBLE,field1:BIGINT>, g0:TIMESTAMP, g1:INTEGER

I0830 00:58:22.226917 3180095 Task.cpp:1647] Terminating task test_cursor 10 with state Failed after running for 9 ms.

buck-out/v2/gen/fbcode/fe0c5a29fd552914/velox/functions/lib/aggregates/__aggregates__/buck-headers/velox/functions/lib/aggregates/AverageAggregateBase.h:259:31: runtime error: signed integer overflo
w: 8490071280492378624 + 8490071280492378624 cannot be represented in type 'long'

    #0 0x7f0806d2ab9d in void facebook::velox::functions::aggregate::AverageAggregateBase<long, double, double>::updateNonNullValue<true>(char*, long, double) fbcode/velox/functions/lib/aggregates/A
verageAggregateBase.h:259
    #1 0x7f0806d2c0bd in void facebook::velox::functions::aggregate::AverageAggregateBase<long, double, double>::addIntermediateResultsImpl<true>(char**, facebook::velox::SelectivityVector const&)::
'lambda0'(int)::operator()(int) const fbcode/velox/functions/lib/aggregates/AverageAggregateBase.h:303
    #2 0x7f0806d29f46 in void facebook::velox::SelectivityVector::applyToSelected<void facebook::velox::functions::aggregate::AverageAggregateBase<long, double, double>::addIntermediateResultsImpl<t
rue>(char**, facebook::velox::SelectivityVector const&)::'lambda0'(int)>(true) const fbcode/velox/vector/SelectivityVector.h:429
    #3 0x7f0806d28968 in void facebook::velox::functions::aggregate::AverageAggregateBase<long, double, double>::addIntermediateResultsImpl<true>(char**, facebook::velox::SelectivityVector const&) f
bcode/velox/functions/lib/aggregates/AverageAggregateBase.h:293
    #4 0x7f0806d1fce5 in facebook::velox::functions::aggregate::AverageAggregateBase<long, double, double>::addIntermediateResults(char**, facebook::velox::SelectivityVector const&, std::vector<std:
:shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > > const&, bool) fbcode/velox/functions/lib/aggregates/AverageAggregateBase.h:219
    #5 0x7f080ad1d2b6 in facebook::velox::exec::AggregateCompanionAdapter::MergeFunction::addRawInput(char**, facebook::velox::SelectivityVector const&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector> > > const&, bool) fbcode/velox/exec/AggregateCompanionAdapter.cpp:121
    #6 0x7f080b0f39d6 in facebook::velox::exec::GroupingSet::addInputForActiveRows(std::shared_ptr<facebook::velox::RowVector> const&, bool) fbcode/velox/exec/GroupingSet.cpp:284
    #7 0x7f080b12702c in facebook::velox::exec::GroupingSet::addInput(std::shared_ptr<facebook::velox::RowVector> const&, bool) fbcode/velox/exec/GroupingSet.cpp:206
    #8 0x7f080b1a11cf in facebook::velox::exec::HashAggregation::addInput(std::shared_ptr<facebook::velox::RowVector>) fbcode/velox/exec/HashAggregation.cpp:205
    #9 0x7f080afe3d29 in facebook::velox::exec::Driver::runInternal(std::shared_ptr<facebook::velox::exec::Driver>&, std::shared_ptr<facebook::velox::exec::BlockingState>&, std::shared_ptr<facebook::velox::RowVector>&) fbcode/velox/exec/Driver.cpp:454

SUMMARY: UndefinedBehaviorSanitizer: signed-integer-overflow buck-out/v2/gen/fbcode/fe0c5a29fd552914/velox/functions/lib/aggregates/__aggregates__/buck-headers/velox/functions/lib/aggregates/AverageAggregateBase.h:259:31
```

CC: @laithsakka @kagamiori 

### System information

n/a

**Comment by mbasmanova** [comment]
Same issue applies to avg_merge_extract_real

**Comment by mbasmanova** [comment]
Same issue applies to avg_merge
