### ISSUE TITLE
Presto min/max(x, n) should restrict n to <= 10'000

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6709]
### Bug description

In Presto, min/max(x, n) functions fail if n > 10'000. In Velox, these queries succeed. Velox needs to match Presto.

```
com.facebook.presto.spi.PrestoException: second argument of max_n/min_n must be less than or equal to 10000; found 5185705558425802603
	at com.facebook.presto.util.Failures.checkCondition(Failures.java:85)
	at com.facebook.presto.operator.aggregation.AbstractMinMaxNAggregationFunction.input(AbstractMinMaxNAggregationFunction.java:130)
	at com.facebook.presto.$gen.IntegerIntegerBigintMinGroupedAccumulator_20230923_162203_1116.addInput(Unknown Source)
```

This issue was discovered by running AggregationFuzzer with Presto as source of truth.

CC: @laithsakka @duanmeng 

### System information

n/a

**Comment by duanmeng** [comment]
@mbasmanova We could add this restriction in `MinMaxNAccumulator::checkAndSetN`.
