### ISSUE TITLE
CircleCI Ubuntu build fails with "undefined symbol: stringToCompressionKind"

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#6813]
### Problem description

My recent PRs all fail with this error on Linux builds. For example https://github.com/facebookincubator/velox/pull/6809 only renamed a variable and most Linux builds failed
```
/root/project/_build/debug/../../velox/common/config/SpillConfig.cpp:50: undefined reference to `facebook::velox::common::stringToCompressionKind(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
```

### System information

Ubuntu 20.04

### CMake log

```bash
See https://app.circleci.com/pipelines/github/facebookincubator/velox/34577/workflows/535e708a-92e8-4018-b92d-b4996da6f831/jobs/226223

make cmake BUILD_DIR=debug BUILD_TYPE=Debug
make[1]: Entering directory '/root/project'
mkdir -p _build/debug && \
cmake -B \
        "_build/debug" \
        -DTREAT_WARNINGS_AS_ERRORS=1 -DENABLE_ALL_WARNINGS=1 -DVELOX_BUILD_MINIMAL="OFF" -DVELOX_BUILD_TESTING="ON" -DCMAKE_BUILD_TYPE=Debug \
        -GNinja -DMAX_LINK_JOBS=5 -DMAX_HIGH_MEM_JOBS=8 \
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
         \
        -DVELOX_ENABLE_ARROW=ON
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /opt/rh/gcc-toolset-9/root/bin/gcc
-- Check for working C compiler: /opt/rh/gcc-toolset-9/root/bin/gcc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/gcc-toolset-9/root/bin/g++
-- Check for working CXX compiler: /opt/rh/gcc-toolset-9/root/bin/g++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type: Debug
-- Disabling Codegen
Setting CMAKE_CXX_FLAGS=-mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2
FINAL CMAKE_CXX_FLAGS= -mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-implicit-fallthrough          -Wno-empty-body          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-array-bounds          -Wno-maybe-uninitialized          -Wno-unused-result          -Wno-format-overflow          -Wno-strict-aliasing          -Wno-type-limits          -Wno-stringop-overflow          -Wno-stringop-overread          -Wno-return-type
-- Setting Boost source to BUNDLED
-- Setting ICU source to BUNDLED
-- Building ICU4C from source
-- Building boost from source
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Boost: Debug build, shared libraries, MPI OFF, Python OFF, testing OFF
-- Boost: libraries included: atomic;context;date_time;filesystem;program_options;regex;system;thread;crc;circular_buffer;math;multi_index;numeric_conversion;random;uuid;variant
CMake Warning at _build/debug/_deps/boost-src/tools/cmake/include/BoostRoot.cmake:205 (message):
  Library 'numeric_conversion' given in BOOST_INCLUDE_LIBRARIES has not been
  found.
Call Stack (most recent call first):
  _build/debug/_deps/boost-src/CMakeLists.txt:20 (include)


-- Performing Test BOOST_ATOMIC_TARGET_X86
-- Performing Test BOOST_ATOMIC_TARGET_X86 - Success
-- Performing Test BOOST_ATOMIC_COMPILER_HAS_SSE2
-- Performing Test BOOST_ATOMIC_COMPILER_HAS_SSE2 - Success
-- Performing Test BOOST_ATOMIC_COMPILER_HAS_SSE41
-- Performing Test BOOST_ATOMIC_COMPILER_HAS_SSE41 - Success
-- Boost.Context: architecture x86_64, binary format elf, ABI sysv, assembler gas, suffix .S, implementation fcontext
-- The ASM compiler identification is GNU
-- Found assembler: /opt/rh/gcc-toolset-9/root/bin/gcc
-- Performing Test BOOST_FILESYSTEM_HAS_INIT_PRIORITY
-- Performing Test BOOST_FILESYSTEM_HAS_INIT_PRIORITY - Success
-- Performing Test BOOST_FILESYSTEM_HAS_CXX20_ATOMIC_REF
....

[1789/1911] Linking CXX executable velox/exec/tests/aggregate_companion_functions_test
FAILED: velox/exec/tests/aggregate_companion_functions_test 
: && /opt/rh/gcc-toolset-9/root/bin/g++  -mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-implicit-fallthrough          -Wno-empty-body          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-array-bounds          -Wno-maybe-uninitialized          -Wno-unused-result          -Wno-format-overflow          -Wno-strict-aliasing          -Wno-type-limits          -Wno-stringop-overflow          -Wno-stringop-overread          -Wno-return-type -Werror -g  -Wl,-export-dynamic velox/exec/tests/CMakeFiles/aggregate_companion_functions_test.dir/AggregateCompanionAdapterTest.cpp.o velox/exec/tests/CMakeFiles/aggregate_companion_functions_test.dir/AggregateCompanionSignaturesTest.cpp.o velox/exec/tests/CMakeFiles/aggregate_companion_functions_test.dir/DummyAggregateFunction.cpp.o  -o velox/exec/tests/aggregate_companion_functions_test  -Wl,-rpath,/root/project/_build/debug/_deps/boost-build/libs/random:/root/project/_build/debug/_deps/boost-build/libs/serialization:/root/project/_build/debug/_deps/boost-build/libs/context:/root/project/_build/debug/_deps/boost-build/libs/filesystem:/root/project/_build/debug/_deps/boost-build/libs/program_options:/root/project/_build/debug/_deps/boost-build/libs/thread:/root/project/_build/debug/_deps/boost-build/libs/atomic:/root/project/_build/debug/_deps/boost-build/libs/date_time:/root/project/_build/debug/_deps/boost-build/libs/chrono:/root/project/_build/debug/_deps/boost-build/libs/container  velox/exec/libvelox_exec.a  velox/functions/libvelox_function_registry.a  lib/libgtest.a  lib/libgtest_main.a  velox/codegen/libvelox_codegen.a  velox/exec/libvelox_exec.a  velox/codegen/libvelox_codegen.a  velox/common/compression/libvelox_common_compression.a  velox/expression/libvelox_expression.a  velox/core/libvelox_core.a  velox/connectors/libvelox_connector.a  velox/common/config/libvelox_spill_config.a  velox/vector/arrow/libvelox_arrow_bridge.a  velox/common/caching/libvelox_caching.a  velox/common/file/libvelox_file.a  velox/core/libvelox_config.a  velox/expression/libvelox_expression_functions.a  velox/expression/type_calculation/libvelox_type_calculation.a  velox/functions/lib/libvelox_functions_util.a  velox/vector/libvelox_vector.a  velox/buffer/libvelox_buffer.a  velox/common/memory/libvelox_memory.a  velox/common/time/libvelox_time.a  velox/common/testutil/libvelox_test_util.a  velox/type/libvelox_type.a  velox/common/base/libvelox_common_base.a  velox/common/encode/libvelox_encode.a  velox/type/tz/libvelox_type_tz.a  velox/common/serialization/libvelox_serialization.a  velox/external/date/libvelox_external_date.a  _deps/re2-build/libre2.a  velox/common/base/libvelox_exception.a  velox/common/process/libvelox_process.a  _deps/folly-build/libfolly.a  _deps/boost-build/libs/random/libboost_random.so.1.81.0  _deps/boost-build/libs/serialization/libboost_serialization.so.1.81.0  _deps/boost-build/libs/context/libboost_context.so.1.81.0  _deps/boost-build/libs/filesystem/libboost_filesystem.so.1.81.0  _deps/boost-build/libs/program_options/libboost_program_options.so.1.81.0  _deps/boost-build/libs/thread/libboost_thread.so.1.81.0  _deps/boost-build/libs/atomic/libboost_atomic.so.1.81.0  _deps/boost-build/libs/date_time/libboost_date_time.so.1.81.0  _deps/boost-build/libs/chrono/libboost_chrono.so.1.81.0  _deps/boost-build/libs/container/libboost_container.so.1.81.0  _deps/boost-build/libs/exception/libboost_exception.a  /usr/lib64/libdouble-conversion.so  _deps/gflags-build/libgflags_debug.a  _deps/glog-build/libglogd.a  /usr/lib64/libevent.so  /usr/lib64/libz.so  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  /usr/lib64/liblz4.so  /usr/lib64/libzstd.so  /usr/local/lib64/libsnappy.a  /usr/lib64/libdwarf.so  /usr/lib64/libsodium.so  -ldl  _deps/fmt-build/libfmtd.a  _deps/glog-build/libglogd.a  _deps/gflags-build/libgflags_nothreads_debug.a  lib/libgtest.a  -pthread && :
velox/common/config/libvelox_spill_config.a(SpillConfig.cpp.o): In function `facebook::velox::common::SpillConfig::SpillConfig(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, folly::Executor*, int, int, unsigned char, unsigned char, unsigned char, bool, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/root/project/_build/debug/../../velox/common/config/SpillConfig.cpp:50: undefined reference to `facebook::velox::common::stringToCompressionKind(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
[1790/1911] Linking CXX executable velox/dwio/dwrf/test/velox_dwio_dwrf_decryption_test
[1791/1911] Building CXX object velox/functions/prestosql/registration/CMakeFiles/velox_functions_prestosql.dir/GeneralFunctionsRegistration.cpp.o
[1792/1911] Linking CXX executable velox/dwio/dwrf/test/velox_dwio_dwrf_checksum_test
[1793/1911] Building CXX object velox/functions/prestosql/registration/CMakeFiles/velox_functions_prestosql.dir/BinaryFunctionsRegistration.cpp.o
[1794/1911] Linking CXX executable velox/dwio/dwrf/test/velox_dwio_dwrf_compression_test
[1795/1911] Building CXX object velox/functions/prestosql/registration/CMakeFiles/velox_functions_prestosql.dir/HyperLogFunctionsRegistration.cpp.o
[1796/1911] Building CXX object velox/functions/prestosql/registration/CMakeFiles/velox_functions_prestosql.dir/MapFunctionsRegistration.cpp.o
[1797/1911] Linking CXX executable velox/dwio/dwrf/test/velox_dwio_dwrf_column_reader_test
[1798/1911] Building CXX object velox/functions/prestosql/registration/CMakeFiles/velox_functions_prestosql.dir/CheckedArithmeticRegistration.cpp.o
[1799/1911] Building CXX object velox/functions/prestosql/registration/CMakeFiles/velox_functions_prestosql.dir/JsonFunctionsRegistration.cpp.o
[1800/1911] Building CXX object velox/functions/prestosql/registration/CMakeFiles/velox_functions_prestosql.dir/StringFunctionsRegistration.cpp.o
[1801/1911] Building CXX object velox/functions/prestosql/registration/CMakeFiles/velox_functions_prestosql.dir/DateTimeFunctionsRegistration.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:94: build] Error 1
make[1]: Leaving directory '/root/project'
make: *** [Makefile:98: debug] Error 2

Exited with code exit status 2
```

```
: && /usr/bin/c++ -mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-implicit-fallthrough          -Wno-empty-body          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-array-bounds          -Wno-maybe-uninitialized          -Wno-unused-result          -Wno-format-overflow          -Wno-strict-aliasing          -Wno-type-limits          -Wno-stringop-overflow          -Wno-stringop-overread          -Wno-return-type -Werror -O3 -DNDEBUG -Wl,-export-dynamic velox/exec/benchmarks/CMakeFiles/velox_exec_vector_hasher_benchmark.dir/VectorHasherBenchmark.cpp.o -o velox/exec/benchmarks/velox_exec_vector_hasher_benchmark  velox/exec/libvelox_exec.a  velox/vector/tests/utils/libvelox_vector_test_lib.a  _deps/folly-build/folly/libfollybenchmark.a  velox/exec/libvelox_exec.a  velox/codegen/libvelox_codegen.a  velox/exec/libvelox_exec.a  velox/codegen/libvelox_codegen.a  velox/common/compression/libvelox_common_compression.a  velox/expression/libvelox_expression.a  velox/core/libvelox_core.a  velox/connectors/libvelox_connector.a  velox/common/config/libvelox_spill_config.a  velox/vector/arrow/libvelox_arrow_bridge.a  velox/common/caching/libvelox_caching.a  velox/common/file/libvelox_file.a  velox/core/libvelox_config.a  velox/expression/libvelox_expression_functions.a  velox/expression/type_calculation/libvelox_type_calculation.a  velox/functions/lib/libvelox_functions_util.a  velox/vector/libvelox_vector.a  velox/buffer/libvelox_buffer.a  velox/common/memory/libvelox_memory.a  velox/common/time/libvelox_time.a  velox/common/testutil/libvelox_test_util.a  velox/type/libvelox_type.a  velox/common/base/libvelox_common_base.a  velox/common/encode/libvelox_encode.a  velox/type/tz/libvelox_type_tz.a  velox/common/serialization/libvelox_serialization.a  velox/common/base/libvelox_exception.a  velox/common/process/libvelox_process.a  _deps/folly-build/libfolly.a  _deps/fmt-build/libfmt.a  /usr/lib/x86_64-linux-gnu/libboost_context.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.74.0  /usr/lib/x86_64-linux-gnu/libdouble-conversion.so  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  /usr/lib/x86_64-linux-gnu/libglog.so  /usr/lib/x86_64-linux-gnu/libevent.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libssl.so  /usr/lib/x86_64-linux-gnu/libcrypto.so  /usr/lib/x86_64-linux-gnu/libbz2.so  /usr/lib/x86_64-linux-gnu/liblz4.so  /usr/lib/x86_64-linux-gnu/libzstd.so  /usr/lib/x86_64-linux-gnu/libsnappy.so  /usr/lib/x86_64-linux-gnu/libsodium.so  -ldl  /usr/lib/x86_64-linux-gnu/libunwind.so  /usr/lib/x86_64-linux-gnu/libglog.so  velox/external/date/libvelox_external_date.a  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  -lpthread  /usr/lib/x86_64-linux-gnu/libre2.so  /usr/lib/x86_64-linux-gnu/libre2.so  lib/libgtest_main.a  lib/libgtest.a && :
/usr/bin/ld: velox/common/config/libvelox_spill_config.a(SpillConfig.cpp.o): in function `facebook::velox::common::SpillConfig::SpillConfig(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, folly::Executor*, int, int, unsigned char, unsigned char, unsigned char, bool, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
```

```
   [1081/1081] : && /opt/rh/gcc-toolset-9/root/bin/g++ -fPIC -mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -g  -Wl,-export-dynamic -shared  -o ../lib.linux-x86_64-cpython-37/pyvelox/pyvelox.cpython-37m-x86_64-linux-gnu.so pyvelox/CMakeFiles/pyvelox.dir/pyvelox.cpp.o pyvelox/CMakeFiles/pyvelox.dir/serde.cpp.o pyvelox/CMakeFiles/pyvelox.dir/signatures.cpp.o pyvelox/CMakeFiles/pyvelox.dir/conversion.cpp.o  -Wl,-rpath,/root/project/_build/lib.linux-x86_64-cpython-37/pyvelox:  velox/type/libvelox_type.a  velox/vector/libvelox_vector.a  velox/core/libvelox_core.a  velox/exec/libvelox_exec.a  velox/functions/prestosql/registration/libvelox_functions_prestosql.a  velox/parse/libvelox_parse_parser.a  velox/functions/prestosql/registration/libvelox_functions_prestosql.a  velox/functions/sparksql/libvelox_functions_spark.a  velox/duckdb/conversion/libvelox_duckdb_parser.a  velox/parse/libvelox_parse_expression.a  velox/exec/libvelox_exec.a  velox/codegen/libvelox_codegen.a  velox/exec/libvelox_exec.a  velox/codegen/libvelox_codegen.a  velox/common/compression/libvelox_common_compression.a  velox/parse/libvelox_parse_utils.a  velox/functions/libvelox_function_registry.a  velox/duckdb/conversion/libvelox_duckdb_conversion.a  velox/external/duckdb/tpch/libtpch_extension.a  velox/external/duckdb/tpch/dbgen/libdbgen.a  velox/external/duckdb/libduckdb.a  velox/functions/prestosql/libvelox_functions_prestosql_impl.a  velox/common/hyperloglog/libvelox_common_hyperloglog.a  velox/functions/prestosql/json/libvelox_functions_json.a  _deps/simdjson-build/libsimdjson.a  velox/external/md5/libmd5.a  velox/functions/prestosql/types/libvelox_presto_types.a  velox/functions/lib/libvelox_is_null_functions.a  velox/expression/libvelox_expression.a  velox/core/libvelox_core.a  velox/vector/arrow/libvelox_arrow_bridge.a  velox/common/caching/libvelox_caching.a  velox/common/file/libvelox_file.a  velox/connectors/libvelox_connector.a  velox/core/libvelox_config.a  velox/common/config/libvelox_spill_config.a  velox/expression/libvelox_expression_functions.a  velox/expression/type_calculation/libvelox_type_calculation.a  velox/functions/lib/libvelox_functions_lib.a  velox/functions/lib/libvelox_functions_util.a  velox/vector/libvelox_vector.a  velox/buffer/libvelox_buffer.a  velox/common/memory/libvelox_memory.a  velox/type/libvelox_type.a  velox/type/tz/libvelox_type_tz.a  velox/common/encode/libvelox_encode.a  velox/common/serialization/libvelox_serialization.a  velox/external/date/libvelox_external_date.a  _deps/re2-build/libre2.a  velox/common/time/libvelox_time.a  velox/common/testutil/libvelox_test_util.a  velox/common/base/libvelox_common_base.a  velox/common/base/libvelox_exception.a  velox/common/process/libvelox_process.a  _deps/folly-build/libfolly.a  ../lib.linux-x86_64-cpython-37/pyvelox/libboost_random.so.1.81.0  ../lib.linux-x86_64-cpython-37/pyvelox/libboost_serialization.so.1.81.0  ../lib.linux-x86_64-cpython-37/pyvelox/libboost_context.so.1.81.0  ../lib.linux-x86_64-cpython-37/pyvelox/libboost_filesystem.so.1.81.0  ../lib.linux-x86_64-cpython-37/pyvelox/libboost_program_options.so.1.81.0  ../lib.linux-x86_64-cpython-37/pyvelox/libboost_thread.so.1.81.0  ../lib.linux-x86_64-cpython-37/pyvelox/libboost_atomic.so.1.81.0  ../lib.linux-x86_64-cpython-37/pyvelox/libboost_date_time.so.1.81.0  ../lib.linux-x86_64-cpython-37/pyvelox/libboost_container.so.1.81.0  ../lib.linux-x86_64-cpython-37/pyvelox/libboost_chrono.so.1.81.0  _deps/boost-build/libs/exception/libboost_exception.a  /usr/lib64/libdouble-conversion.so  _deps/gflags-build/libgflags_debug.a  _deps/glog-build/libglogd.a  /usr/lib64/libevent.so  /usr/lib64/libz.so  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  /usr/lib64/liblz4.so  /usr/lib64/libzstd.so  /usr/local/lib64/libsnappy.a  /usr/lib64/libdwarf.so  /usr/lib64/libsodium.so  -ldl  _deps/fmt-build/libfmtd.a  _deps/glog-build/libglogd.a  _deps/gflags-build/libgflags_nothreads_debug.a  -pthread && :
    _build/temp.linux-x86_64-cpython-37
    copying _build/lib.linux-x86_64-cpython-37/pyvelox/pyvelox.cpython-37m-x86_64-linux-gnu.so -> pyvelox
    Creating /root/.conda/envs/pyveloxenv/lib/python3.7/site-packages/pyvelox.egg-link (link to .)
    Adding pyvelox 0.0.1a0+bd151a2 to easy-install.pth file

    Installed /root/project
Successfully installed cffi-1.15.1 mypy-extensions-1.0.0 numpy-1.21.6 pyarrow-12.0.1 pycparser-2.21 pyvelox-0.0.1a0+bd151a2 tabulate-0.9.0 typing-3.7.4.3 typing-extensions-4.7.1 typing-inspect-0.9.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/tmp/signature.py", line 18, in <module>
    import pyvelox.pyvelox as pv
ImportError: /root/project/pyvelox/pyvelox.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN8facebook5velox6common23stringToCompressionKindERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by yingsu00** [comment]
Attempted fix: https://github.com/facebookincubator/velox/pull/6812

**Comment by kgpai** [comment]
Thanks @yingsu00 , theres already a fix landing : https://github.com/facebookincubator/velox/pull/6807

**Comment by yingsu00** [comment]
@kgpai Are you sure https://github.com/facebookincubator/velox/pull/6807 fixes all issues? There is another failure here:
```
  File "/tmp/signature.py", line 18, in <module>
    import pyvelox.pyvelox as pv
ImportError: /root/project/pyvelox/pyvelox.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN8facebook5velox6common23stringToCompressionKindERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```
Was this one also fixed

**Comment by assignUser** [comment]
Closing as I don't see the error happening on main anymore.
