### ISSUE TITLE
 No registered file system matched with file path 'hdfs://host:8020'

### ISSUE THREAD

**Issue by guyuqi** [facebookincubator/velox#7652]
### Bug description

When I run TPC-DS wwith Spark SQL queries from some parquet files in HDFS,  the issues occurred:

```
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: No registered file system matched with file path 'hdfs://wls-arm-huawei04:8020/spark/TPC-DS_DATA/item/part-00000-1e0bc6fe-8058-44cb-a8a2-09400b6d122d-c000.snappy.parquet'
Retriable: False
Context: Split [Hive: hdfs://wls-arm-huawei04:8020/spark/TPC-DS_DATA/item/part-00000-1e0bc6fe-8058-44cb-a8a2-09400b6d122d-c000.snappy.parquet 12582912 - 4194304] Task Gluten [Stage: 38 TID: 12099]
Top-Level Context: Same as context.
Function: getFileSystem
File: /home/hadoop/spark-gluten-velox/gluten/ep/build-velox/build/velox_ep/velox/common/file/FileSystems.cpp
Line: 61
Stack trace:
.....
```

May I ask if HDFS was supported by Velox or not?

### System information

OS: Ubuntu-22.04
Arch: Arm64
Spark version: 3.3.1

### Relevant logs

```bash
23/11/20 17:35:19 WARN TaskSetManager: Lost task 2.1 in stage 38.0 (TID 12096) (host1 executor 3): io.glutenproject.exception.GlutenException: java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: No registered file system matched with file path 'hdfs://host1:8020/spark/TPC-DS_DATA/item/part-00000-1e0bc6fe-8058-44cb-a8a2-09400b6d122d-c000.snappy.parquet'
Retriable: False
Context: Split [Hive: hdfs://host1:8020/spark/TPC-DS_DATA/item/part-00000-1e0bc6fe-8058-44cb-a8a2-09400b6d122d-c000.snappy.parquet 8388608 - 4194304] Task Gluten [Stage: 38 TID: 12096]
Top-Level Context: Same as context.
Function: getFileSystem
File: /home/hadoop/spark-gluten-velox/gluten/ep/build-velox/build/velox_ep/velox/common/file/FileSystems.cpp
Line: 61
Stack trace:
# 0  facebook::velox::VeloxException::VeloxException(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, facebook::velox::VeloxException::Type, std::basic_string_view<char, std::char_traits<char> >)
# 1  void facebook::velox::detail::veloxCheckFail<facebook::velox::VeloxRuntimeError, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(facebook::velox::detail::VeloxCheckFailArgs const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# 2  facebook::velox::filesystems::getFileSystem(std::basic_string_view<char, std::char_traits<char> >, std::shared_ptr<facebook::velox::Config const>)
# 3  facebook::velox::FileHandleGenerator::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# 4  facebook::velox::CachedFactory<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<facebook::velox::FileHandle>, facebook::velox::FileHandleGenerator>::generate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# 5  facebook::velox::connector::hive::HiveDataSource::addSplit(std::shared_ptr<facebook::velox::connector::ConnectorSplit>)
# 6  facebook::velox::exec::TableScan::getOutput()
# 7  facebook::velox::exec::Driver::runInternal(std::shared_ptr<facebook::velox::exec::Driver>&, std::shared_ptr<facebook::velox::exec::BlockingState>&, std::shared_ptr<facebook::velox::RowVector>&)
# 8  facebook::velox::exec::Driver::next(std::shared_ptr<facebook::velox::exec::BlockingState>&)
# 9  facebook::velox::exec::Task::next(folly::SemiFuture<folly::Unit>*)
# 10 gluten::WholeStageResultIterator::next()
# 11 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 12 0x0000ffff98015828

	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:39)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
	at io.glutenproject.utils.InvocationFlowProtection.hasNext(Iterators.scala:137)
	at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:69)
	at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:35)
	at io.glutenproject.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at io.glutenproject.backendsapi.velox.SparkPlanExecApiImpl.$anonfun$createBroadcastRelation$1(SparkPlanExecApiImpl.scala:289)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:855)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:855)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:365)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:329)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Exception: VeloxRuntimeError
```

**Comment by majetideepak** [comment]
You have to build Velox with `-DVELOX_ENABLE_HDFS=ON`
