### ISSUE TITLE
 JsonFunctionsTest.jsonParse  stack-buffer-overflow 

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#7886]
### Description

```
Note: Google Test filter = JsonFunctionsTest.jsonParse
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from JsonFunctionsTest
[ RUN      ] JsonFunctionsTest.jsonParse

=================================================================
==327322==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fca6ef2eb64 at pc 0x7fca7b86a0dd bp 0x7ffc63f9bc70 sp 0x7ffc63f9bc68
READ of size 64 at 0x7fca6ef2eb64 thread T0
SCARINESS: 51 (multi-byte-read-stack-buffer-overflow-far-from-bounds)
    #0 0x7fca7b86a0dc in simdjson::icelake::(anonymous namespace)::simd::base8_numeric<unsigned char>::load(unsigned char const*) third-party/simdjson/singleheader/simdjson.h:14242
    #1 0x7fca7b87ff89 in simdjson::icelake::(anonymous namespace)::simd::simd8<unsigned char>::simd8(unsigned char const*) third-party/simdjson/singleheader/simdjson.h:14372
    #2 0x7fca7b887c57 in simdjson::icelake::(anonymous namespace)::backslash_and_quote::copy_and_find(unsigned char const*, unsigned char*) third-party/simdjson/singleheader/simdjson.h:14720
    #3 0x7fca7b886aff in simdjson::icelake::(anonymous namespace)::stringparsing::parse_string(unsigned char const*, unsigned char*, bool) third-party/simdjson/singleheader/simdjson.cpp:8329
    #4 0x7fca7b886732 in simdjson::icelake::(anonymous namespace)::stage2::tape_builder::visit_string(simdjson::icelake::(anonymous namespace)::stage2::json_iterator&, unsigned char const*, bool) third-party/simdjson/singleheader/simdjson.cpp:9085
    #5 0x7fca7b8860e6 in simdjson::icelake::(anonymous namespace)::stage2::tape_builder::visit_root_string(simdjson::icelake::(anonymous namespace)::stage2::json_iterator&, unsigned char const*) third-party/simdjson/singleheader/simdjson.cpp:9095
    #6 0x7fca7b886032 in simdjson::error_code simdjson::icelake::(anonymous namespace)::stage2::json_iterator::visit_root_primitive<simdjson::icelake::(anonymous namespace)::stage2::tape_builder>(simdjson::icelake::(anonymous namespace)::stage2::tape_builder&, unsigned char const*) third-party/simdjson/singleheader/simdjson.cpp:8798
    #7 0x7fca7b8853c4 in simdjson::icelake::(anonymous namespace)::stage2::tape_builder::visit_root_primitive(simdjson::icelake::(anonymous namespace)::stage2::json_iterator&, unsigned char const*) third-party/simdjson/singleheader/simdjson.cpp:9034
    #8 0x7fca7b882dc6 in simdjson::error_code simdjson::icelake::(anonymous namespace)::stage2::json_iterator::walk_document<false, simdjson::icelake::(anonymous namespace)::stage2::tape_builder>(simdjson::icelake::(anonymous namespace)::stage2::tape_builder&) third-party/simdjson/singleheader/simdjson.cpp:8654
    #9 0x7fca7b882620 in simdjson::error_code simdjson::icelake::(anonymous namespace)::stage2::tape_builder::parse_document<false>(simdjson::icelake::dom_parser_implementation&, simdjson::dom::document&) third-party/simdjson/singleheader/simdjson.cpp:9030
    #10 0x7fca7b8514cc in simdjson::icelake::dom_parser_implementation::stage2(simdjson::dom::document&) third-party/simdjson/singleheader/simdjson.cpp:9254
    #11 0x7fca7b8513e6 in simdjson::icelake::dom_parser_implementation::parse(unsigned char const*, unsigned long, simdjson::dom::document&) third-party/simdjson/singleheader/simdjson.cpp:9272
    #12 0x7fca8d226f23 in simdjson::dom::parser::parse_into_document(simdjson::dom::document&, unsigned char const*, unsigned long, bool) & fbsource/simdjson/singleheader/simdjson.h:8882
    #13 0x7fca8d226a8a in simdjson::dom::parser::parse(unsigned char const*, unsigned long, bool) & fbsource/simdjson/singleheader/simdjson.h:8901
    #14 0x7fca8d224eee in simdjson::dom::parser::parse(char const*, unsigned long, bool) & fbsource/simdjson/singleheader/simdjson.h:8905
    #15 0x7fca8d22eeed in auto facebook::velox::functions::(anonymous namespace)::JsonParseFunction::apply(facebook::velox::SelectivityVector const&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector>>>&, std::shared_ptr<facebook::velox::Type const> const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) const::'lambda'(auto)::operator()<int>(auto) const fbcode/velox/functions/prestosql/JsonFunctions.cpp:107
    #16 0x7fca8d2253cc in void facebook::velox::SelectivityVector::applyToSelected<facebook::velox::functions::(anonymous namespace)::JsonParseFunction::apply(facebook::velox::SelectivityVector const&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector>>>&, std::shared_ptr<facebook::velox::Type const> const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) const::'lambda'(auto)>(auto) const fbcode/velox/vector/SelectivityVector.h:429
    #17 0x7fca8d2238d7 in facebook::velox::functions::(anonymous namespace)::JsonParseFunction::apply(facebook::velox::SelectivityVector const&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector>>>&, std::shared_ptr<facebook::velox::Type const> const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) const fbcode/velox/functions/prestosql/JsonFunctions.cpp:105
    #18 0x7fca8faff222 in facebook::velox::exec::Expr::applyFunction(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/Expr.cpp:1487
    #19 0x7fca8fb0f3a2 in facebook::velox::exec::Expr::evalAllImpl(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/Expr.cpp:1415
    #20 0x7fca8fb05076 in facebook::velox::exec::Expr::evalAll(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/Expr.cpp:1360
    #21 0x7fca8fb083b3 in facebook::velox::exec::Expr::evalWithNulls(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/Expr.cpp:1150
    #22 0x7fca8fb05701 in facebook::velox::exec::Expr::evalEncodings(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) fbcode/velox/expression/Expr.cpp:1072
    #23 0x7fca8fb0497b in facebook::velox::exec::Expr::eval(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&, facebook::velox::exec::ExprSet const*) fbcode/velox/expression/Expr.cpp:855
    #24 0x7fca8fac9987 in facebook::velox::exec::ExprSet::eval(int, int, bool, facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector>>>&) fbcode/velox/expression/Expr.cpp:1893
    #25 0xce32c1 in facebook::velox::exec::ExprSet::eval(facebook::velox::SelectivityVector const&, facebook::velox::exec::EvalCtx&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector>>>&) fbcode/velox/expression/Expr.h:678
    #26 0xce1ecc in facebook::velox::functions::test::FunctionBaseTest::evaluate(facebook::velox::exec::ExprSet&, std::shared_ptr<facebook::velox::RowVector> const&, std::optional<facebook::velox::SelectivityVector> const&) fbcode/velox/functions/prestosql/tests/utils/FunctionBaseTest.h:244
    #27 0xce163c in std::shared_ptr<facebook::velox::BaseVector> facebook::velox::functions::test::FunctionBaseTest::evaluateImpl<facebook::velox::exec::ExprSet>(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, std::shared_ptr<facebook::velox::RowVector> const&, std::optional<facebook::velox::SelectivityVector> const&) fbcode/velox/functions/prestosql/tests/utils/FunctionBaseTest.h:303
    #28 0xce0ea7 in facebook::velox::functions::test::FunctionBaseTest::evaluate(std::shared_ptr<facebook::velox::core::ITypedExpr const> const&, std::shared_ptr<facebook::velox::RowVector> const&, std::optional<facebook::velox::SelectivityVector> const&) fbcode/velox/functions/prestosql/tests/utils/FunctionBaseTest.h:76
    #29 0xce02d6 in facebook::velox::functions::test::FunctionBaseTest::evaluate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::shared_ptr<facebook::velox::RowVector> const&, std::optional<facebook::velox::SelectivityVector> const&) fbcode/velox/functions/prestosql/tests/utils/FunctionBaseTest.h:86
    #30 0xed7de8 in std::shared_ptr<facebook::velox::SimpleVector<facebook::velox::StringView>> facebook::velox::functions::test::FunctionBaseTest::evaluate<facebook::velox::SimpleVector<facebook::velox::StringView>>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::shared_ptr<facebook::velox::RowVector> const&, std::optional<facebook::velox::SelectivityVector> const&, std::shared_ptr<facebook::velox::Type const> const&) fbcode/velox/functions/prestosql/tests/utils/FunctionBaseTest.h:119
    #31 0x2152cb8 in std::optional<facebook::velox::StringView> facebook::velox::functions::test::FunctionBaseTest::evaluateOnce<facebook::velox::StringView>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::shared_ptr<facebook::velox::RowVector>, std::optional<facebook::velox::SelectivityVector> const&, std::shared_ptr<facebook::velox::Type const> const&) fbcode/velox/functions/prestosql/tests/utils/FunctionBaseTest.h:201
    #32 0x21525d9 in std::optional<facebook::velox::StringView> facebook::velox::functions::test::FunctionBaseTest::evaluateOnce<facebook::velox::StringView, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> const&) fbcode/velox/functions/prestosql/tests/utils/FunctionBaseTest.h:172
    #33 0x215142d in facebook::velox::functions::prestosql::(anonymous namespace)::JsonFunctionsTest_jsonParse_Test::TestBody()::$_1::operator()(std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>) const fbcode/velox/functions/prestosql/tests/JsonFunctionsTest.cpp:184
    #34 0x214981e in facebook::velox::functions::prestosql::(anonymous namespace)::JsonFunctionsTest_jsonParse_Test::TestBody() fbcode/velox/functions/prestosql/tests/JsonFunctionsTest.cpp:195
    #35 0x7fca93edd89e in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) fbsource/src/gtest.cc:2675
    #36 0x7fca93edd124 in testing::Test::Run() fbsource/src/gtest.cc:2692
    #37 0x7fca93ee2d5f in testing::TestInfo::Run() fbsource/src/gtest.cc:2841
    #38 0x7fca93eead16 in testing::TestSuite::Run() fbsource/src/gtest.cc:3020
    #39 0x7fca93f2667b in testing::internal::UnitTestImpl::RunAllTests() fbsource/src/gtest.cc:5925
    #40 0x7fca93f256db in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) fbsource/src/gtest.cc:2675
    #41 0x7fca93f24c19 in testing::UnitTest::Run() fbsource/src/gtest.cc:5489
    #42 0x7fca93db69a0 in RUN_ALL_TESTS() fbsource/gtest/gtest.h:2317
    #43 0x7fca93db662f in main fbcode/common/gtest/LightMain.cpp:20
    #44 0x7fca7c22c656 in __libc_start_call_main /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #45 0x7fca7c22c717 in [__libc_start_main@GLIBC_2.2.5](mailto:__libc_start_main@GLIBC_2.2.5) /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../csu/libc-start.c:409:3
    #46 0xb29360 in _start /home/engshare/third-party2/glibc/2.34/src/glibc-2.34/csu/../sysdeps/x86_64/start.S:116

Address 0x7fca6ef2eb64 is located in stack of thread T0 at offset 100 in frame
    #0 0x7fca8d22ec8f in auto facebook::velox::functions::(anonymous namespace)::JsonParseFunction::apply(facebook::velox::SelectivityVector const&, std::vector<std::shared_ptr<facebook::velox::BaseVector>, std::allocator<std::shared_ptr<facebook::velox::BaseVector>>>&, std::shared_ptr<facebook::velox::Type const> const&, facebook::velox::exec::EvalCtx&, std::shared_ptr<facebook::velox::BaseVector>&) const::'lambda'(auto)::operator()<int>(auto) const fbcode/velox/functions/prestosql/JsonFunctions.cpp:105

  This frame has 2 object(s):
    [32, 48) 'value' (line 106)
    [64, 88) 'parsed' (line 107) <== Memory access at offset 100 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow third-party/simdjson/singleheader/simdjson.h:14242 in simdjson::icelake::(anonymous namespace)::simd::base8_numeric<unsigned char>::load(unsigned char const*)
Shadow bytes around the buggy address:
  0x0ff9cddddd10: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff9cddddd20: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff9cddddd30: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff9cddddd40: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff9cddddd50: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x0ff9cddddd60: f1 f1 f1 f1 00 00 f2 f2 00 00 00 f3[f3]f3 f3 f3
  0x0ff9cddddd70: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff9cddddd80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0ff9cddddd90: f1 f1 f1 f1 00 00 00 00 f2 f2 f2 f2 00 00 f3 f3
  0x0ff9cddddda0: f1 f1 f1 f1 00 f2 f2 f2 00 f2 f2 f2 00 00 f3 f3
  0x0ff9cdddddb0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==327322==ABORTING
```

### Error Reproduction

Meta only :
https://www.internalfb.com/sandcastle/workflow/1139410705726327955

**Comment by Yuhta** [comment]
Fixed in #7858
