### ISSUE TITLE
exchange source error when  response to exchange client request

### ISSUE THREAD

**Issue by heary-cloud** [facebookincubator/velox#7983]
### Bug description

**Expected behavior:**
not core dump stack
**actual behavior:**
```
#11 0x00007fe671e32276 in std::__1::shared_ptr<facebook::velox::exec::ExchangeSource>::shared_ptr[abi:v160000](std::__1::shared_ptr<facebook::velox::exec::ExchangeSource> const&) (this=<optimized out>, __r=...)
    at ./libcxx/include/__memory/shared_ptr.h:596
#12 std::__1::allocator<std::__1::shared_ptr<facebook::velox::exec::ExchangeSource> >::construct[abi:v160000]<std::__1::shared_ptr<facebook::velox::exec::ExchangeSource>, std::__1::shared_ptr<facebook::velox::exec::ExchangeSource> const&>(std::__1::shared_ptr<facebo
ok::velox::exec::ExchangeSource>*, std::__1::shared_ptr<facebook::velox::exec::ExchangeSource> const&) (this=<optimized out>, __p=<optimized out>, __args=...) at ./libcxx/include/__memory/allocator.h:165
#13 std::__1::allocator_traits<std::__1::allocator<std::__1::shared_ptr<facebook::velox::exec::ExchangeSource> > >::construct[abi:v160000]<std::__1::shared_ptr<facebook::velox::exec::ExchangeSource>, std::__1::shared_ptr<facebook::velox::exec::ExchangeSource> const&
, void>(std::__1::allocator<std::__1::shared_ptr<facebook::velox::exec::ExchangeSource> >&, std::__1::shared_ptr<facebook::velox::exec::ExchangeSource>*, std::__1::shared_ptr<facebook::velox::exec::ExchangeSource> const&) (__a=..., __p=<optimized out>, __args=...)
    at ./libcxx/include/__memory/allocator_traits.h:290
#14 std::__1::deque<std::__1::shared_ptr<facebook::velox::exec::ExchangeSource>, std::__1::allocator<std::__1::shared_ptr<facebook::velox::exec::ExchangeSource> > >::push_back (this=<optimized out>, __v=...) at ./libcxx/include/deque:1794
#15 std::__1::queue<std::__1::shared_ptr<facebook::velox::exec::ExchangeSource>, std::__1::deque<std::__1::shared_ptr<facebook::velox::exec::ExchangeSource>, std::__1::allocator<std::__1::shared_ptr<facebook::velox::exec::ExchangeSource> > > >::push[abi:v160000](std
::__1::shared_ptr<facebook::velox::exec::ExchangeSource> const&) (this=<optimized out>, __v=...) at ./libcxx/include/queue:360
#16 0x00007fe671e32276 in facebook::velox::exec::ExchangeClient::request(facebook::velox::exec::ExchangeClient::RequestSpec const&)::$_0::operator()<facebook::velox::exec::ExchangeSource::Response>(facebook::velox::exec::ExchangeSource::Response&&) const (
    this=0x7f9c580af090, response=...)
#17 folly::futures::detail::wrapInvoke<facebook::velox::exec::ExchangeSource::Response, facebook::velox::exec::ExchangeClient::request(facebook::velox::exec::ExchangeClient::RequestSpec const&)::$_0>(folly::Try<facebook::velox::exec::ExchangeSource::Response>&&, fac
ebook::velox::exec::ExchangeClient::request(facebook::velox::exec::ExchangeClient::RequestSpec const&)::$_0&&)::{lambda()#1}::operator()() const (this=<optimized out>) at ./folly/futures/Future-inl.h:90
#18 folly::futures::detail::InvokeResultWrapper<void>::wrapResult<folly::futures::detail::wrapInvoke<facebook::velox::exec::ExchangeSource::Response, facebook::velox::exec::ExchangeClient::request(facebook::velox::exec::ExchangeClient::RequestSpec const&)::$_0>(foll
y::Try<facebook::velox::exec::ExchangeSource::Response>&&, facebook::velox::exec::ExchangeClient::request(facebook::velox::exec::ExchangeClient::RequestSpec const&)::$_0&&)::{lambda()#1}>(folly::futures::detail::wrapInvoke<facebook::velox::exec::ExchangeSource::Resp
onse, facebook::velox::exec::ExchangeClient::request(facebook::velox::exec::ExchangeClient::RequestSpec const&)::$_0>(folly::Try<facebook::velox::exec::ExchangeSource::Response>&&, facebook::velox::exec::ExchangeClient::request(facebook::velox::exec::ExchangeClient:
:RequestSpec const&)::$_0&&)::{lambda()#1}) (fn=...) at ./futures/Future-inl.h:82
#19 folly::futures::detail::wrapInvoke<facebook::velox::exec::ExchangeSource::Response, facebook::velox::exec::ExchangeClient::request(facebook::velox::exec::ExchangeClient::RequestSpec const&)::$_0>(folly::Try<facebook::velox::exec::ExchangeSource::Response>&&, fac
ebook::velox::exec::ExchangeClient::request(facebook::velox::exec::ExchangeClient::RequestSpec const&)::$_0&&) (t=..., f=...) at ./futures/Future-inl.h:100
#20 folly::Future<facebook::velox::exec::ExchangeSource::Response>::thenValue<facebook::velox::exec::ExchangeClient::request(facebook::velox::exec::ExchangeClient::RequestSpec const&)::$_0>(facebook::velox::exec::ExchangeClient::request(facebook::velox::exec::Exchan
geClient::RequestSpec const&)::$_0&&) &&::{lambda(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<facebook::velox::exec::ExchangeSource::Response>&&)#1}::operator()(folly::Executor::KeepAlive<folly::Executor>&&, folly::Try<facebook::velox::exec::ExchangeSo
urce::Response>&&) (this=0x7f9c580af090, t=...) at ./futures/Future-inl.h:985
```

### System information

Query Testing

**Comment by mbasmanova** [comment]
CC: @Yuhta @spershin @amitkdutta @xiaoxmeng
