### ISSUE TITLE
UndefinedBehaviorSanitizer: out-of-bounds-index in decimal divide

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#9362]
### Bug description

```
TEST_F(DecimalArithmeticTest, xxx) {
  // DECIMAL(20, 1) / DECIMAL(33, 32)

  auto a = makeFlatVector<int128_t>({5000, 20000}, DECIMAL(20, 1));
  auto b = makeFlatVector<int128_t>({5000, 20000}, DECIMAL(33, 32));

  auto result = evaluate("divide(c0, c1)", makeRowVector({a, b}));
  LOG(ERROR) << result->toString();
  LOG(ERROR) << result->toString(0, 10);
}

[ RUN      ] DecimalArithmeticTest.xxx

velox/type/DecimalUtil.h:293:11: runtime error: index 63 out of bounds for type 'const facebook::velox::int128_t[39]' (aka 'const __int128[39]')
    #0 0x7f256bef7c31 in __int128 facebook::velox::DecimalUtil::divideWithRoundUp<__int128, __int128, __int128>(__int128&, __int128, __int128, bool, unsigned char, unsigned char) fbcode/velox/type/DecimalUtil.h:293
    #1 0x7f256bef6ac5 in void facebook::velox::functions::(anonymous namespace)::DecimalDivideFunction<facebook::velox::exec::VectorExec>::call<__int128, __int128, __int128>(__int128&, __int128 const&, __int128 const&) fbcode/velox/functions/prestosql/DecimalFunctions.cpp:183

SUMMARY: UndefinedBehaviorSanitizer: out-of-bounds-index buck-out/v2/gen/fbcode/80f97405942d59b0/velox/type/__velox_type__/buck-headers/velox/type/DecimalUtil.h:293:11 in 
```

This issue was discovered by running Expression Fuzzer extended to support decimal types. See #9149

CC: @majetideepak @rui-mo @kgpai @kagamiori 

### System information

n/a

**Comment by mbasmanova** [comment]
CC: @karteekmurthys

**Comment by karteekmurthys** [comment]
Parameters have precision and scale as follows:

*A precision, scale:* 20,1
*B precision, scale:* 32, 32
*Result p,s :* 38, 32
*Rescale factor:* 32 - 1 + 32 = 63

```
 inline static uint8_t
  computeRescaleFactor(uint8_t fromScale, uint8_t toScale, uint8_t rScale) {
    return rScale - fromScale + toScale;
  } 
```
The high rescale factor is causing the issue: We don't have entries beyond index:38 in the array: `DecimalUtil::kPowersOfTen[aRescale]`

```
unsignedDividendRescaled = checkedMultiply<R>(
        unsignedDividendRescaled,
        R(DecimalUtil::kPowersOfTen[aRescale]), <-- aRescale=63 and goes out of bounds.
        "Decimal"
```

**Comment by karteekmurthys** [comment]
I ran a similar test case on Presto. This leads to overflow issue:

```
presto:test> insert into tbig values(decimal'500', decimal'0.00000000000000000000000000005');
INSERT: 1 row

Query 20240404_181659_00018_4h9vu, FINISHED, 1 node
Splits: 35 total, 35 done (100.00%)
[Latency: client-side: 0:03, server-side: 0:03] [0 rows, 0B] [0 rows/s, 0B/s]

presto:test> select c0/c1 from tbig;

Query 20240404_181709_00019_4h9vu, FAILED, 1 node
Splits: 17 total, 0 done (0.00%)
[Latency: client-side: 0:01, server-side: 0:01] [0 rows, 0B] [0 rows/s, 0B/s]

Query 20240404_181709_00019_4h9vu failed: Decimal overflow
```
It is expected, the final result doesn't fit in Long Decimal (scale 38 vs 63). May be we must gracefully handle this case.

**Comment by mbasmanova** [comment]
@rui-mo @PHILO-HE Folks, do you know if Spark's decimal divide function has a similar issue?

**Comment by rui-mo** [comment]
@mbasmanova Spark works as below as it adjusts the result scale to 6.
```
spark.sql("select cast(500.0 as decimal(20, 1)) / cast(0.00000000000000000000000000005000 as decimal(33, 32))").show(false)
+------------------------------------------------------------------+            
|(CAST(500.0 AS DECIMAL(20,1)) / CAST(5.000E-29 AS DECIMAL(33,32)))|
+------------------------------------------------------------------+
|10000000000000000000000000000000.000000                           |
+------------------------------------------------------------------+
```

Also verified Velox's implementation of decimal divide for Spark, it works as below.
```
  testDecimalExpr<TypeKind::HUGEINT>(
      makeNullableLongDecimalVector(
          {"1" + std::string(31, '0'), "1" + std::string(31, '0')},
          DECIMAL(38, 6)),
      "divide(c0, c1)",
      {makeFlatVector<int128_t>({5000, 20000}, DECIMAL(20, 1)),
       makeFlatVector<int128_t>({5000, 20000}, DECIMAL(33, 32))}); 
```
Results are aligned between Velox and Spark for this case.

**Comment by mbasmanova** [comment]
@rui-mo Rui, thank you for checking and clarifying. I see that Spark has a different formula for calculating result precision and scale of division. I wonder if there is an explanation of these formulas somewhere. We have recently documented these formulas for Presto: https://facebookincubator.github.io/velox/functions/presto/decimal.html It would be nice at some point to document these for Spark. Thanks.

**Comment by mbasmanova** [comment]
@rui-mo Thank you, Rui.
