### ISSUE TITLE
Crash in IcebergSplitReader when SplitPreload enabled

### ISSUE THREAD

**Issue by zhli1142015** [facebookincubator/velox#9545]
### Bug description

I encountered a crash in gluten UT, when enabling the split preloading: https://github.com/apache/incubator-gluten/actions/runs/8748743592/job/24009286393?pr=5456 .
Crash dump in my local repro:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139812729837120) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139812729837120) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139812729837120, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f2a17092476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f2a170787f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f2a164414b7 in ?? () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#6  0x00007f2a16d88891 in ?? () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#7  0x00007f2a16bd4faa in JVM_handle_linux_signal ()
   from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#8  0x00007f2a16bc80fc in ?? () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#9  <signal handler called>
#10 0x00007f28bd9b9823 in facebook::velox::AlignedBuffer::allocate<signed char> (numElements=512,
    pool=0x74756c672f746967, initValue=std::optional<signed char> [no contained value])
    at /var/git/gluten/ep/build-velox/build/velox_ep/./velox/buffer/Buffer.h:320
#11 0x00007f28c5430679 in facebook::velox::dwio::common::ensureCapacity<signed char> (data=..., capacity=512,
    pool=0x74756c672f746967) at /var/git/gluten/ep/build-velox/build/velox_ep/./velox/dwio/common/BufferUtil.h:30
#12 0x00007f28c542fc6f in facebook::velox::connector::hive::iceberg::IcebergSplitReader::next (this=0x7f283c00a290,
    size=4096, output=std::shared_ptr<facebook::velox::BaseVector> (use count 1, weak count 0) = {...})
    at /var/git/gluten/ep/build-velox/build/velox_ep/velox/connectors/hive/iceberg/IcebergSplitReader.cpp:101
#13 0x00007f28bdda0a45 in facebook::velox::connector::hive::HiveDataSource::next (this=0x7f2860cf7bf0, size=4096)
```

memory pool address in frame10: `0x74756c672f746967`.
```
#10 0x00007f28bd9b9823 in facebook::velox::AlignedBuffer::allocate<signed char> (numElements=512,
    pool=0x74756c672f746967, initValue=std::optional<signed char> [no contained value])
    at /var/git/gluten/ep/build-velox/build/velox_ep/./velox/buffer/Buffer.h:320
320         std::cout << "preferredSize:" << pool->preferredSize(checkedPlus<size_t>(size, kPaddedSize)) << std::endl;
(gdb) print pool
$1 = (facebook::velox::memory::MemoryPool *) 0x74756c672f746967
```

memory pool address in `SplitReader`:` 0x7f2860d66ba0`.
```

#12 0x00007f28c542fc6f in facebook::velox::connector::hive::iceberg::IcebergSplitReader::next (this=0x7f283c00a290,
    size=4096, output=std::shared_ptr<facebook::velox::BaseVector> (use count 1, weak count 0) = {...})
    at /var/git/gluten/ep/build-velox/build/velox_ep/velox/connectors/hive/iceberg/IcebergSplitReader.cpp:101
101         dwio::common::ensureCapacity<int8_t>(
(gdb) print *this
$2 = {<facebook::velox::connector::hive::SplitReader> = {
    _vptr.SplitReader = 0x7f28cfa40b28 <vtable for facebook::velox::connector::hive::iceberg::IcebergSplitReader+16>,
    hiveSplit_ = std::shared_ptr<const facebook::velox::connector::hive::HiveConnectorSplit> (use count 3, weak count 0) = {get() = 0x7f2860dec2f0},
    hiveTableHandle_ = std::shared_ptr<const facebook::velox::connector::hive::HiveTableHandle> (use count 6, weak count 0) = {
      get() = 0x7f2860d63c10}, partitionKeys_ = 0x7f283c00d5c8, connectorQueryCtx_ = 0x7f2860d9a980,
    hiveConfig_ = std::shared_ptr<const facebook::velox::connector::hive::HiveConfig> (use count 7, weak count 0) = {
      get() = 0x7f2a1324a210},
    readerOutputType_ = std::shared_ptr<const facebook::velox::RowType> (use count 1, weak count 0) = {get() = 0x7f283c00eaf0},
    ioStats_ = std::shared_ptr<facebook::velox::io::IoStatistics> (use count 16, weak count 0) = {
      get() = 0x7f283c00a150}, fileHandleFactory_ = 0x7f2a1324a148, executor_ = 0x7f2a13248d40,
    pool_ = 0x7f2860d66ba0,
    scanSpec_ = std::shared_ptr<facebook::velox::common::ScanSpec> (use count 4, weak count 0) = {get() = 0x7f283c00d7e0},

```

These two addresses should be same but they are different. This issue is because `ConnectorQueryCtx` is created in [line 311](https://github.com/facebookincubator/velox/blob/3f5db597f6d99616c0fb98218dfd0322fe7a708d/velox/exec/TableScan.cpp#L311) and captured by the lambda. After async source `move`, the function is released and also the `ctx` is released . So the `connectorQueryCtx_` in `SplitReader` becomes a dangling pointer. And `IcebergSplitReader` uses it in `next` method and triggers the crash.

### System information

Velox System Info v0.0.2
Commit: 3f5db597f6d99616c0fb98218dfd0322fe7a708d
CMake Version: 3.22.1
System: Linux-5.15.146.1-microsoft-standard-WSL2
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by zhli1142015** [comment]
@Yuhta  and @yingsu00 , could you please help take a look, https://github.com/facebookincubator/velox/pull/9544?
Thanks.
