### ISSUE TITLE
Failure in  Fuzzer Jobs / Build (pull_request)

### ISSUE THREAD

**Issue by zhli1142015** [facebookincubator/velox#9622]
### Problem description

Please describe how you were trying to build velox and what issue occured
CI
https://github.com/facebookincubator/velox/actions/runs/8829306332/job/24240039890?pr=9415

```
Comparing spark signatures...
Traceback (most recent call last):
  File "/__w/velox/velox/velox/scripts/signature.py", line 381, in <module>
    sys.exit(main())
  File "/__w/velox/velox/velox/scripts/signature.py", line 377, in main
    return globals()[args.command](args)
  File "/__w/velox/velox/velox/scripts/signature.py", line 223, in bias_aggregates
    with open(args.base) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/signatures/presto_aggregate_signatures_main.json'
```

### System information

Velox System Info v0.0.2
Commit: 2dda33198196f666be6952d5d9125ef84c225b81
CMake Version: 3.22.1
System: Linux-5.15.146.1-microsoft-standard-WSL2
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

### CMake log

```bash
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting deepdiff
  Downloading deepdiff-7.0.1-py3-none-any.whl (80 kB)
Collecting ordered-set<4.2.0,>=4.1.0
  Downloading ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Installing collected packages: ordered-set, deepdiff
Successfully installed deepdiff-7.0.1 ordered-set-4.1.0
WARNING: You are using pip version 20.2.4; however, version 24.0 is available.
You should consider upgrading via the '/__w/velox/velox/velox/.venv/bin/python3 -m pip install --upgrade pip' command.
Exporting presto signatures...
Exporting spark signatures...
Comparing presto signatures...
No differences found.
 No changes detected: Nothing to do!
Comparing spark signatures...
Traceback (most recent call last):
  File "/__w/velox/velox/velox/scripts/signature.py", line 381, in <module>
    sys.exit(main())
  File "/__w/velox/velox/velox/scripts/signature.py", line 377, in main
    return globals()[args.command](args)
  File "/__w/velox/velox/velox/scripts/signature.py", line 223, in bias_aggregates
    with open(args.base) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/signatures/presto_aggregate_signatures_main.json'
```

**Comment by mbasmanova** [comment]
@kgpai Krishna, would you help take a look?

CC: @pedroerp @assignUser

**Comment by kgpai** [comment]
@zhli1142015 Can you rebase against latest main and see if you still get these errors ?

**Comment by kgpai** [comment]
Looks like it did not run the baseline job , to checkout main etc. Investigating why thats the case.
